### ISSUE TITLE
Is your license GPL-3?

### ISSUE THREAD

**Issue by Petross404** [KDAB/hotspot#102]
Hi, I want to package hotspot for Gentoo and I have to know exactly under which license hotspot is offered. Can you please help me? :-)

PS Nice software!

**Comment by krf** [comment]
Hotspot is available under both the GNU GPL v2 (or any later version) as well as under a commercial license.

@milianw We should probably add a note about the license to the top-level README.

**Comment by Petross404** [comment]
Thank you very much.

**Comment by Petross404** [comment]
Here is the ebuild. https://github.com/Petross404/testing/blob/master/dev-util/hotspot/hotspot-1.1.0.ebuild

It's not yet accepted,but other users May use it with a personal overlay
