### ISSUE TITLE
Hotspot Flamegraph does not show sample count on hover

### ISSUE THREAD

**Issue by chsterz** [KDAB/hotspot#105]
Instead the estimated cost in <event> is reported.
This is misleading and leads to wrong statistical assumptions.
![screenshot from 2017-11-24 14-18-26](https://user-images.githubusercontent.com/315665/33212308-be3d94f6-d122-11e7-8e58-f24effcf0179.png)

**Comment by milianw** [comment]
I improved the flame graph tooltips a bit now, but note that the 5.391E+6 is correct as we use the cycle count as weight for each sample. I.e. the above doesn't mean 5.391E+6 samples but that all samples taken together had a weight of 5.391E+6 cycles.

Suggestions on how to improve that wording are welcome. For now I'll close this.
