### ISSUE TITLE
Missing tst_addresscache.cpp file

### ISSUE THREAD

**Issue by andikleen** [KDAB/hotspot#109]
With current HEAD cmake configuration fails with:

I suppose it's a problem in the upstream perfparser

-- Configuring done
CMake Error at /usr/share/ECM/modules/ECMAddTests.cmake:110 (add_executable):
  Cannot find source file:

    perfparser/tests/auto/addresscache/tst_addresscache.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  3rdparty/perfparser.cmake:50 (ecm_add_test)
  3rdparty/CMakeLists.txt:1 (include)

CMake Error at 3rdparty/perfparser.cmake:7 (add_executable):
  Cannot find source file:

    perfparser/app/perfaddresscache.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  3rdparty/CMakeLists.txt:1 (include)

**Comment by andikleen** [comment]
This works as a w/a:

diff --git a/3rdparty/perfparser b/3rdparty/perfparser
index b12133e..24477d5 160000
--- a/3rdparty/perfparser
+++ b/3rdparty/perfparser
@@ -1 +1 @@
-Subproject commit b12133e7b835c0feefa296f709e622f63574a465
+Subproject commit 24477d53301fd8198e52d2fa54e627c92c176340
diff --git a/3rdparty/perfparser.cmake b/3rdparty/perfparser.cmake
index 60b5658..72d0cdf 100644
--- a/3rdparty/perfparser.cmake
+++ b/3rdparty/perfparser.cmake
@@ -17,7 +17,6 @@ add_executable(hotspot-perfparser
     perfparser/app/perfsymboltable.cpp
     perfparser/app/perfelfmap.cpp
     perfparser/app/perfkallsyms.cpp
-    perfparser/app/perfaddresscache.cpp
 )
 
 target_link_libraries(hotspot-perfparser
@@ -47,20 +46,6 @@ ecm_add_test(
         tst_elfmap
 )
 
-ecm_add_test(
-    perfparser/tests/auto/addresscache/tst_addresscache.cpp
-    perfparser/app/perfelfmap.cpp
-    perfparser/app/perfaddresscache.cpp
-    LINK_LIBRARIES
-        Qt5::Core
-        Qt5::Network
-        Qt5::Test
-        ${LIBDW_LIBRARIES}
-        ${LIBELF_LIBRARIES}
-    TEST_NAME
-        tst_addresscache
-)
-
 ecm_add_test(
     perfparser/tests/auto/kallsyms/tst_kallsyms.cpp
     perfparser/app/perfkallsyms.cpp

**Comment by andikleen** [comment]
well it would work if github didn't destroy the patch.

basically remove all references to the addresscache in 3rdparty/perfparser.cmake

**Comment by andikleen** [comment]
Ok it works when I blow away the git checkout.

Seems some coherency problem with the submodule.

**Comment by milianw** [comment]
did you try to update the git submodule? odd failure, I wonder what the reason was except an outdated submodule hm
