### ISSUE TITLE
compilation of test failed

### ISSUE THREAD

**Issue by facontidavide** [KDAB/hotspot#110]
I am trying to compile the master head in Ubunet 16.04.
I get 

> [ 88%] Linking CXX executable ../../bin/tst_perfparser
> CMakeFiles/tst_perfparser.dir/tst_perfparser.cpp.o: In function `TestPerfParser::testPerfData(Data::Symbol const&, Data::Symbol const&, QString const&, bool)':
> tst_perfparser.cpp:(.text._ZN14TestPerfParser12testPerfDataERKN4Data6SymbolES3_RK7QStringb[_ZN14TestPerfParser12testPerfDataERKN4Data6SymbolES3_RK7QStringb]+0x834): undefined reference to `bool QTest::qCompare<unsigned int, int>(unsigned int const&, int const&, char const*, char const*, char const*, int)'
> tst_perfparser.cpp:(.text._ZN14TestPerfParser12testPerfDataERKN4Data6SymbolES3_RK7QStringb[_ZN14TestPerfParser12testPerfDataERKN4Data6SymbolES3_RK7QStringb]+0x198b): undefined reference to `bool QTest::qCompare<int, unsigned int>(int const&, unsigned int const&, char const*, char const*, char const*, int)'
> CMakeFiles/tst_perfparser.dir/tst_perfparser.cpp.o: In function `TestPerfParser::testOffCpu()':
> tst_perfparser.cpp:(.text._ZN14TestPerfParser10testOffCpuEv[_ZN14TestPerfParser10testOffCpuEv]+0x3f7): undefined reference to `bool QTest::qCompare<QString, char [7]>(QString const&, char const (&) [7], char const*, char const*, char const*, int)'
> tst_perfparser.cpp:(.text._ZN14TestPerfParser10testOffCpuEv[_ZN14TestPerfParser10testOffCpuEv]+0x473): undefined reference to `bool QTest::qCompare<QString, char [19]>(QString const&, char const (&) [19], char const*, char const*, char const*, int)'
> tst_perfparser.cpp:(.text._ZN14TestPerfParser10testOffCpuEv[_ZN14TestPerfParser10testOffCpuEv]+0x4ca): undefined reference to `bool QTest::qCompare<QString, char [13]>(QString const&, char const (&) [13], char const*, char const*, char const*, int)'
> collect2: error: ld returned 1 exit status
> tests/integrationtests/CMakeFiles/tst_perfparser.dir/build.make:224: recipe for target 'bin/tst_perfparser' failed
> make[2]: *** [bin/tst_perfparser] Error 1
> CMakeFiles/Makefile2:1565: recipe for target 'tests/integrationtests/CMakeFiles/tst_perfparser.dir/all' failed
> make[1]: *** [tests/integrationtests/CMakeFiles/tst_perfparser.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed

**Comment by facontidavide** [comment]
Deleted. Travis already tells you that ;)

**Comment by milianw** [comment]
fixed now
