### ISSUE TITLE
Implement support for diff-ing Flame Graphs

### ISSUE THREAD

**Issue by oparvu** [KDAB/hotspot#112]
It could be potentially useful to implement support for `diff`-ing Flame Graphs in Hotspot.

Example usage scenario (that could be integrated into a project's CI workflow):
1. Profile application before commit C => Flame Graph FG1.
2. Profile application after commit C => Flame Graph FG2.
3. `diff` FG1 and FG2 to visualize C's (significant) effects on performance.

Potentially useful related work:
1. [Differential Flame Graphs](http://www.brendangregg.com/blog/2014-11-09/differential-flame-graphs.html).

**Comment by milianw** [comment]
This should be expanded to all views, not only flame graphs. See also: #37

I'm closing this task.
