### ISSUE TITLE
perfparser can't parse /proc/kallsyms with "(null)"

### ISSUE THREAD

**Issue by BigBigos** [KDAB/hotspot#114]
At least my /proc/kallsyms file starts with:

```
$ cat /proc/kallsyms
          (null) A irq_stack_union
          (null) A __per_cpu_start
...
```

The perfparser fails at the "(null)" lines. I have worked it around locally by adding simple `if (address == "(null)") continue;` line to perfkallsyms.cpp, not sure if that is correct handling.

**Comment by milianw** [comment]
fixed now
