### ISSUE TITLE
Unable to widen "Symbol" column in Top Down view

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#116]
It seems impossible to make the "Symbol" column in the Top Down view wider. Hovering over the header doesn't show a resize indicator for that column.
In a very deep call tree, this prevents the user from properly reading the symbol name - see attached screenshot. In addition, I can not right-click the header to hide the other columns, which would also save some space.

**Comment by tmcguire** [comment]
![hotspot_column](https://user-images.githubusercontent.com/1164876/35813991-45ef684c-0a95-11e8-8a38-e8356c643897.png)

**Comment by milianw** [comment]
agreed, I've run into this myself. I believe it's a bug/limitation upstream in Qt arising from the call to `setSectionResizeMode(0, QHeaderView::Stretch)` in `resultsutil.cpp`. Try to remove that call, does that help? Thing is, the view right now looks OK as the default, but it should still be possible to manually change the column widths. Suggestions welcome on how to handle this.

**Comment by baryluk** [comment]
The logic for resizing columns is bit weird and counter intuitive for other columns too. I.e. to resize "Binary" column you can't drag the left side of the binary column and drag it left to make it larger, instead you need to grab the right side and move it right, but when doing so, the right side stays in place, and left moves. Weird!

BTW. Great tool. I like it! :)
