### ISSUE TITLE
Kernel symbols broken unless explicitly specificing --kallsyms

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#117]
When I run hotspot without a command line argument, all kernel symbols are broken and resolved to a random name. See screenshot.

Invoking hotspot with the following works:

```
cat /proc/kallsyms > kallsysms
hotspot --kallsyms kallsysms
```

As a user I expect this to be happening automatically.
The proc file is readable by all users:

```
$ ls -lah /proc/kallsyms
-r--r--r-- 1 root root 0  5. Feb 16:59 /proc/kallsyms
```

![kallsyms_broken](https://user-images.githubusercontent.com/1164876/35814183-bd82a540-0a95-11e8-96da-191d0ef440fc.png)

**Comment by milianw** [comment]
please debug this on your system - it works for me here. Can you try to add debug output to see what perfparser sees when reading /proc/kallsyms directly, vs. what it sees after you've copied the file?

**Comment by tmcguire** [comment]
The issue was a stale kallsyms file in ~/.debug, which contained only zero as entries. I've fixed this now by ignoring entries with address zero.
