### ISSUE TITLE
No way to specify DWARF unwinding size

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#118]
Quite often backtraces in large Qt applications are broken because they don't fit into the default 8192 size of stack. This makes the flame graph and top down view of the affected parts quite incorrect.
Therefore, as a user I'd like to specify a larger size, for example with `--call-graph dwarf,16384`. This is not possible in the UI, I can only select the unwinding method, but not enter additional parameters.

**Comment by milianw** [comment]
agreed, that should be added. the default should be auto, maybe use a similar approach to the GUI I added for `-m`

**Comment by lievenhey** [comment]
The feature is now implemented
