### ISSUE TITLE
Packaging for Ubuntu

### ISSUE THREAD

**Issue by kecsap** [KDAB/hotspot#127]
It was not a big thing, I packaged this software in my PPA:

https://launchpad.net/~csaba-kertesz/+archive/ubuntu/random

**Comment by milianw** [comment]
ok, cool. I guess you reported the issue here to have that information added to the Readme? What version of Ubuntu are you targeting?

**Comment by kecsap** [comment]
Yes, if you want you can add this information to the README. I target now Ubuntu Xenial, but I will support 18.04 LTS once it is released.

**Comment by sylvestre** [comment]
I would be happy to sponsor the package in Debian and then request a sync into Ubuntu so that it is in the official repos.

**Comment by krf** [comment]
@sylvestre Well, please go ahead! :)

**Comment by kecsap** [comment]
It was a little work. Feel free to use. If you give some credit, it is appreciated.

**Comment by milianw** [comment]
since this isn't really a bug on our end, I'm closing this. feel free to send in a pull request for updated README instructions once the package is officially uploaded to the debian/ubuntu repos.

thanks!
