### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by pager72** [KDAB/hotspot#129]
Cloned git repo followed build instructions ran:
`git clone git@github.com:KDAB/hotspot.git && mkdir build-hotspot && cd build-hotspot && cmake ../hotspot && make`
and failure:
[Build log](https://bugs.kde.org/attachment.cgi?id=111953)

**Comment by krf** [comment]
The build instructions you've used are correct. You should be getting a different output though. Please post exactly what you get in your terminal when invoking above commands.

**Comment by pager72** [comment]
Here we go:
https://paste.pound-python.org/show/OJfXzJOW5VKFxgxdewPT/

**Comment by milianw** [comment]
Read the text and run the command it tells you to run?

```
      git submodule update --init --recursive
```

**Comment by pager72** [comment]
i did its in the paste

On Apr 13, 2018 12:52 PM, "Milian Wolff" <notifications@github.com> wrote:

Read the text and run the command it tells you to run?

      git submodule update --init --recursive

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KDAB/hotspot/issues/129#issuecomment-381244187>, or mute
the thread

**Comment by pager72** [comment]
If you read this carefully it shows that I did run it
https://paste.pound-python.org/show/mT1bUUmqkG7WdA8VYMt5/

**Comment by milianw** [comment]
And if you read the error message carefully, you should notice that you are running the command in the wrong folder. Note source directory != build directory.

**Comment by pager72** [comment]
I finally built it. Please add hotspot to kdab overlay.
