### ISSUE TITLE
Add hotspot to kdab gentoo overlay

### ISSUE THREAD

**Issue by pager72** [KDAB/hotspot#130]
I cannot build hotspot with git alone because its buggy however Im sure the overlay method will somehow just work. Hotspot will help me debug my bug https://bugs.kde.org/show_bug.cgi?id=392988 hotspot bug didn't help https://github.com/KDAB/hotspot/issues/129

**Comment by krf** [comment]
@DaveeFTW Worth adding an ebuild for Hotspot to our overlay, maybe?

**Comment by DaveeFTW** [comment]
Absolutely, I'll look into it.

**Comment by krf** [comment]
Any updates here?

**Comment by farmboy0** [comment]
https://github.com/farmboy0/portage-overlay/tree/master/dev-util/hotspot

**Comment by milianw** [comment]
so all done? closing

**Comment by milianw** [comment]
https://github.com/KDAB/kdab-overlay/tree/master/dev-util/hotspot btw too
