### ISSUE TITLE
Recording does not start (when perf executable is missing)

### ISSUE THREAD

**Issue by pager72** [KDAB/hotspot#131]
Added screencast, zipped video file.
[issue.zip](https://github.com/KDAB/hotspot/files/1913726/issue.zip)

Nothing happens after I hit record, and it wont even stop after I hit it again. No logfile is made in specified directory also.

**Comment by pager72** [comment]
Ran as root issue persists. Refer to screencast.
[bla.zip](https://github.com/KDAB/hotspot/files/1917422/bla.zip)

**Comment by krf** [comment]
@milianw This is likely caused by a missing `perf` executable. I can reproduce this when the `perf` binary is missing.

**Comment by milianw** [comment]
@pager72 in your screencast you pasted the shell command into the "event type" command line which is utterly wrong. Please paste the command I have shown *into a console*. Outside of hotspot. Can you confirm Kevins idea? Do you even have perf installed?

**Comment by pager72** [comment]
Trying to build perf, but no instructions in
https://github.com/KDAB/perfparser

**Comment by pager72** [comment]
Installed perf, hotspot works.

**Comment by pager72** [comment]
Its out of the scope for this bug.
