### ISSUE TITLE
Does hotspot need to be run off of the same system as where perf was used?

### ISSUE THREAD

**Issue by andyd0** [KDAB/hotspot#134]
I'm able to read the report data on the host server but when I try to look at the data output in hotspot in a Ubuntu VM I get lots of errors regarding missing symbols.  I'm unable to use the tool on the server so was hoping I could use the data recorded on something locally.

![image](https://user-images.githubusercontent.com/7110426/39130588-80d951de-46db-11e8-9fe8-3f39af9733de.png)

**Comment by milianw** [comment]
you essentially have to copy the debug information data from the server to your local machine. Try to use `perf archive` for that. Alternatively copy the debug info files by hand into a "sysroot" folder and then use `hotspot --sysroot ...`. You'll also have to copy the `/proc/kallsyms` file over.
