### ISSUE TITLE
"Off-CPU Profiling" checkbox missing from record page when perf manpages are missing

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#135]
In the "Record" dialog, I don't see a "Off-CPU Profiling" checkbox.
I think the reason is that I compiled perf from sources, and didn't install the new manpages. Therefore `perf --help` will fall back to the outdated manpages of the perf installed via distribution packages. Hotspot seems to parse the `--help` output to check if off-cpu profiling is available (see a4dceae79b2b653dc2da432a504cfcd66bb2c0e8), and therefore incorrectly thinks my self-compiled perf doesn't support off-cpu profiling.

I realize this is a perf setup issue on my side though.

**Comment by jintiangoodday** [comment]
Is it enough to upgrade perf without upgrading kernel?

**Comment by milianw** [comment]
@jintiangoodday depends on what you want to do?

**Comment by jintiangoodday1** [comment]
> @jintiangoodday depends on what you want to do?

My app runs on linux kernel 3.19 and its perf version does not support "off-cpu", can I upgrade perf but keep 3.19, to support off-cpu?

**Comment by milianw** [comment]
I'm not sure, but I believe this requires some help from the kernel too. but you could first try it out with just updating perf and see if this works then:

```
perf record --switch-events ls
perf script --show-switch-events
```

If that works, then you should be all set.

**Comment by ravenAtSafe** [comment]
It would be great if the GUI would still show the off-cpu option (with a helpful "install perf help" tooltip) when it can't be enabled.  Took me a while to reconcile the readme.md contents with my GUI not having the option.

**Comment by milianw** [comment]
agreed, patches welcome - that should be pretty easy to do :)

**Comment by milianw** [comment]
done nowadays
