### ISSUE TITLE
Comparison of Two Perf Data

### ISSUE THREAD

**Issue by ChetanArvindPatil** [KDAB/hotspot#149]
Hi All,

Hotspot is good at providing visualization of perf data for a specific workload. What if I want to do comparison or diff between same application but more changes to second workload with same code than the first one?

Any suggestions if this can be handled by Hotspot or not?

Thanks.

**Comment by milianw** [comment]
this isn't implemented yet, see also https://github.com/KDAB/hotspot/issues/37
