### ISSUE TITLE
Profiling Deep Learning Framework

### ISSUE THREAD

**Issue by ChetanArvindPatil** [KDAB/hotspot#151]
Hi All,

I am profiling networks on [Intel Caffe](https://github.com/intel/caffe/). The output logs I get have Parser Errors.

Can anyone please help me understand how I can profile without any errors? The `perf.data` I am getting is not helping me dig about software hotspot.

![hotspot](https://user-images.githubusercontent.com/1078444/45243678-a6a74f80-b2a9-11e8-9793-be381da2dedb.png)

Thanks.

**Comment by psteinb** [comment]
Not sure ...but as expected the Intel MKL (math library that 
intel/caffe) used doesn't contain debug symbols. What linux distro is 
this? Depending on this, different strategies for function resolution 
(i.e. call graph recording in perf speak) could be tried:

```
$ perf record --help
#...
--call-graph <mode[,dump_size]>
                           setup and enables call-graph (stack 
chain/backtrace) recording: fp dwarf lbr
#...
```

**Comment by psteinb** [comment]
You could try to decrease the sample frequency for starters:
```
$ perf record -F 20
```
This would put it at 20 Hz IIRC. The default is much higher AFAIK, but I 
just fail to find it in the perf sources.

**Comment by PatilChetan** [comment]
@psteinb 

Thanks.

I am getting data size that is about 1GB. The data looks clean enough to analyze using `perf report`. I am yet to try `hotspot`. 

Can I go below `20` to let says `10`? If yes why if not why not? Pros and cons any?

Appreciate your help.
