### ISSUE TITLE
App Image won't start with ArchLinux (Wayland) 

### ISSUE THREAD

**Issue by chsterz** [KDAB/hotspot#154]
Hi, I tried to launch the AppImage  on my Wayland-defaulting system and it failed with this error message: 
```~$ ./hotspot-v1.1.0-x86_64.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
/tmp/.mount_hotspoAKQ3hy/AppRun: line 3: 10518 Aborted                 
(core dumped) LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$d/usr/bin/hotspot" $@
```

**Comment by chsterz** [comment]
The (temporary) solution for this was to extract the image:
`./hotspot-v1.1.0-x86_64.AppImage --appimage-extract` 
and then delete `.../usr/lib/libfreetype.so.6` from it, so it picks my systems* one.

**Comment by milianw** [comment]
@zvonkok that isn't the latest one, it's just the latest released one. The very latest can be found from https://travis-ci.org/KDAB/hotspot/builds/, then select the latest build and search for the `transfer.sh` link in the build log, e.g.: https://transfer.sh/rxhfI/Hotspot-git.8e277fc-x86_64.AppImage

A new stable release will come soon
