### ISSUE TITLE
The flame graph tab uses the wrong data when "Reset Zoom And Filter"

### ISSUE THREAD

**Issue by sjoubert** [KDAB/hotspot#156]
The wrong data is loaded when the "Reset Zoom And Filter" is used in the Flame Graph > Time Line widget.

* Generate two sets of data: perf.data.foo and perf.data.bar
* Launch hotspot
* File > Open > Select perf.data.foo
* File > Open > Select perf.data.bar
* Go to Flame Graph, select a piece of the timeline and either Zoom In or Filter the selection
* In the Time Line menu "Reset Zoom And Filter" (this does not happen with "Reset Zoom" or "Zoom Out")
* Both the flame graph and the time line load the data from perf.data.foo instead of perf.data.bar

I'm using the hotspot 1.1.0 AppImage

**Comment by milianw** [comment]
afaik I've fixed this already, can you try with the latest appimage from here please: https://transfer.sh/M0vLI/Hotspot-git.a42ee38-x86_64.AppImage

**Comment by sjoubert** [comment]
I confirm this is already fixed, thanks.

Do you plan on making a new release soon and/or is there a way to get the latest AppImages?

**Comment by milianw** [comment]
Yes, I plan to create a new release soon, but I've been saying this for quite some time already. So for now:

- just go to https://travis-ci.org/KDAB/hotspot/builds/
- click on the latest build
- scroll down and search for a `transfer.sh` link similar to the above

cheers
