### ISSUE TITLE
Can't run on Gentoo

### ISSUE THREAD

**Issue by RazrFalcon** [KDAB/hotspot#157]
```
execvp: No such file or directory
```

I'm not sure which package should I install to get it.

Built from https://github.com/KDAB/kdab-overlay

**Comment by milianw** [comment]
You can't run hotspot? Or you can't record your code with perf? What command do you run that triggers the above output?

**Comment by RazrFalcon** [comment]
My bad. This is occurring right after pressing Start Recording in launch Application mode.

**Comment by milianw** [comment]
do you have `perf` installed? maybe this is related to https://github.com/KDAB/hotspot/pull/132 - which I'll rebase and merge now

**Comment by RazrFalcon** [comment]
Actually no. I thought that it will be pulled with dependencies.

This actually fixed my problem. It should be added to the ebuild.

**Comment by milianw** [comment]
ok, we'll fix that - thanks for the report (and sorry for the delay in communications)

**Comment by DaveeFTW** [comment]
I've applied this change to the overlay.
