### ISSUE TITLE
ansible script. feel free to add

### ISSUE THREAD

**Issue by senior7515** [KDAB/hotspot#158]
Hi Guys, 

thanks for hotspot - it's awesome! 

As part of my .dotfiles i wrote this quick ansible script and seems to work for debian/fedora (both latest)

https://gist.github.com/senior7515/15e4fe5f57842cbdee3ef11af6434f28

Not sure if helpful. 

THe nice thing about something like that is that one can simply add it to the `roles/*` and it would work x-platform. 

Feel free to close, just wanted to share.

**Comment by milianw** [comment]
I've never used ansible, and don't want to maintain something I have zero knowledge about. I'll close this now. If you want to maintain it in our upstream repo, please file a proper merge request.

Thanks, hope you don't mind!

**Comment by senior7515** [comment]
yeah all good. just sharing.
