### ISSUE TITLE
[travis] No easy way to download nightly AppImages anymore

### ISSUE THREAD

**Issue by karroffel** [KDAB/hotspot#162]
Apparently transfer.sh changed the way they handle links from uploaded files and now returns the link with a unique identifier added in the URL.

For example

```
$ curl --upload-file test https://transfer.sh/mytestfile
https://transfer.sh/TKgCc/mytestfile
```

The travis script does upload an AppImage file here 
https://github.com/KDAB/hotspot/blob/5447e950886e290a5f29b6af8bf28b6de13f3d30/.travis.yml#L64

and it's possible to figure out the name by using the short commit hash, but the problem is that the travis log does not show the output of the `curl` command as can be seen here:

https://travis-ci.org/KDAB/hotspot/builds/474482640#L9163

The [*raw log*](https://api.travis-ci.org/v3/job/474482641/log.txt) does contain the uploaded link but it's not as straight forward anymore as before.

Would it be possible to explicitly *re-print* the output of that command so it's easier to find when looking at the travis logs?

**Comment by probonopd** [comment]
Alternatively, you could use https://github.com/probonopd/uploadtool to upload continuous builds (each push) to GitHub Releases.

**Comment by milianw** [comment]
@probonopd thanks a lot, I've integrated this now and it works like a charm!

@karroffel see https://github.com/KDAB/hotspot/releases/tag/continuous
