### ISSUE TITLE
"The hotspot-perfparser binary exited with code 8"

### ISSUE THREAD

**Issue by catskul** [KDAB/hotspot#163]
```
hotspot.perfparser: QProcess::ProcessError(Crashed) "Process crashed"
"Process crashed"
"The hotspot-perfparser binary exited with code 8"
```

Dumps core. Gdb reports:

```Program terminated with signal SIGFPE, Arithmetic exception```

Stacktrace is unreadable. (all "??")

Running build of tip of master "5447e950886e290a5f29b6af8bf28b6de13f3d30"

Kernel:

```Linux asomerville-ThinkPad-P50 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by milianw** [comment]
Can you please `strace` hotspot to see the command it uses for `hotspot-perfparser`, then run that one directly from the command line in GDB to see what's going on? Or are you using the AppImage?

**Comment by catskul** [comment]
Strace doesn't seem to show the command line args (I don't see execv)
```
stat("/home/username/tmp/hotspot/bld/lib/x86_64-linux-gnu/libexec/hotspot-perfparser", {st_mode=S_IFREG|0775, st_size=448464, ...}) = 0
access("/home/username/tmp/hotspot/bld/lib/x86_64-linux-gnu/libexec/hotspot-perfparser", X_OK) = 0
```

So I ran that executable assuming `--input perf.data` and it ran returning error `2`:

```
~/tmp/hotspot/bld/lib/x86_64-linux-gnu/libexec/hotspot-perfparser --input perf.data 
QPERFSTREAM 
```

Trying to investigate more to see if I can figure out exactly how hotspot runs it.

**Comment by catskul** [comment]
Thanks!
