### ISSUE TITLE
tons of logging slowing down load of data

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#167]
This is with current master (about an hour ago)

Load seems rather slow, looks like it was going to take about 40mins to load 48G of profile data.

Mostly I think because it's spitting out tons of messages like the ones below to the console:

Some programs use a filter on their output to remove duplicates from their output, or maybe it should be put behind some kind of -verbose flag?

failed to report ElfInfo{localFile="/home/noel/.debug/usr/lib64/libc-2.28.so/534a2a62ff86a0e893ef6748dff3018af42ab3ab/elf", isFile=true, originalFileName="libc-2.28.so", originalPath="/usr/lib64/libc-2.28.so", addr=7f69cc143000, len=1363968, pgoff=139264, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", addr=7f69cc7ae000, len=401408, pgoff=593920, } : Cannot report file fragments
failed to report ElfInfo{localFile="/home/noel/libo/workdir/UnpackedTarball/cppunit/src/cppunit/.libs/libcppunit-1.14.so.0.0.0", isFile=true, originalFileName="libcppunit-1.14.so.0.0.0", originalPath="/home/noel/libo/workdir/UnpackedTarball/cpp

**Comment by grandinj** [comment]
Also lots of

hotspot.perfparser: Unexpected attribute id: -1 Only know about 1 attributes so far

**Comment by milianw** [comment]
I doubt it's the debug output that is slowing hotspotn down (try to profile it yourself :P), but rather it seems like it fails to interpret the mmap structure recorded in your `perf.data` file. We'll have to figure out why that happens... Can you paste the output of the following command please:

    perf script --show-mmap-events |& grep MMAP

Also, 48GB or perf.data is *huge*. Are you sure you need to profile that much data? I.e. even with bugs fixed, it will still take a long time to process 48GB of data. I suggest you try to reduce the sampling rate, or reduce the time you are profiling your application, to reduce the size of the data files.

**Comment by grandinj** [comment]
Oh yes, I know I'm pushing the limits, LibreOffice does that :-) 

Running that commands shows stuff like this:

cppunittester  5002 514088.553244: PERF_RECORD_MMAP2 5002/5002: [0x7f143bba1000(0x11d000) @ 0 fd:02 7473589 2092920959]: r-xp /home/noel/libo2/instdir/program/libspelllo.so
cppunittester  5002 514088.622199: PERF_RECORD_MMAP2 5002/5002: [0x7f143bf1a000(0x42000) @ 0 fd:02 7473588 1916086368]: r-xp /home/noel/libo2/instdir/program/libhyphenlo.so
cppunittester  5002 514088.625437: PERF_RECORD_MMAP2 5002/5002: [0x7f143bb60000(0x41000) @ 0 fd:02 7476364 836527015]: r-xp /home/noel/libo2/instdir/program/liblnthlo.so
cppunittester  5002 514088.644723: PERF_RECORD_MMAP2 5002/5002: [0x7f143b966000(0x1fa000) @ 0 fd:02 7473859 565684642]: r-xp /home/noel/libo2/instdir/program/libdeployment.so
cppunittester  5002 514088.644753: PERF_RECORD_MMAP2 5002/5002: [0x7f143b8f6000(0x70000) @ 0 fd:02 7473584 3761770301]: r-xp /home/noel/libo2/instdir/program/libdeploymentmiscl
o.so
cppunittester  5002 514088.644784: PERF_RECORD_MMAP2 5002/5002: [0x7f143b855000(0xa1000) @ 0 fd:02 7473064 695615484]: r-xp /home/noel/libo2/instdir/program/libhelplinkerlo.so
cppunittester  5002 514088.644915: PERF_RECORD_MMAP2 5002/5002: [0x7f143b7f3000(0x27000) @ 0xa000 fd:00 2241678 3464295312]: r-xp /usr/lib64/libxslt.so.1.1.32
cppunittester  5002 514088.644942: PERF_RECORD_MMAP2 5002/5002: [0x7f143b3ce000(0x41b000) @ 0 fd:02 7480719 1101485859]: r-xp /home/noel/libo2/instdir/program/libclucene.so
cppunittester  5002 514088.693321: PERF_RECORD_MMAP2 5002/5002: [0x7f143adab000(0x5c4000) @ 0 fd:02 7473473 1482007122]: r-xp /home/noel/libo2/instdir/program/libwriterfilterlo
.so
cppunittester  5002 514088.693368: PERF_RECORD_MMAP2 5002/5002: [0x7f143a3db000(0x9d0000) @ 0 fd:02 7476400 4083221300]: r-xp /home/noel/libo2/instdir/program/libooxlo.so
cppunittester  5002 514088.693502: PERF_RECORD_MMAP2 5002/5002: [0x7f143a31c000(0xbf000) @ 0 fd:02 7473242 782161406]: r-xp /home/noel/libo2/instdir/program/libexpwraplo.so
cppunittester  5002 514088.703618: PERF_RECORD_MMAP2 5002/5002: [0x7f143a1f8000(0x124000) @ 0 fd:02 7476239 1003493471]: r-xp /home/noel/libo2/instdir/program/libxstor.so
cppunittester  5002 514088.704208: PERF_RECORD_MMAP2 5002/5002: [0x7f143a19a000(0x5e000) @ 0 fd:02 7471826 3034280248]: r-xp /home/noel/libo2/instdir/program/libreflectionlo.so
cppunittester  5002 514088.706640: PERF_RECORD_MMAP2 5002/5002: [0x7f143a11b000(0x7f000) @ 0 fd:02 7471835 818475803]: r-xp /home/noel/libo2/instdir/program/libunordflo.so
cppunittester  5002 514088.706669: PERF_RECORD_MMAP2 5002/5002: [0x7f143a0df000(0x2e000) @ 0xe000 fd:02 7480932 573487569]: r-xp /home/noel/libo2/instdir/program/librdf-lo.so.0
cppunittester  5002 514088.706701: PERF_RECORD_MMAP2 5002/5002: [0x7f143a08b000(0x2d000) @ 0x11000 fd:02 7480754 2097141686]: r-xp /home/noel/libo2/instdir/program/libraptor2-l
o.so.0

**Comment by grandinj** [comment]
This is perf version 4.19.14 running on Fedora 29, btw

**Comment by milianw** [comment]
yes, I will need the full output of this command, in order to inspect it to reproduce the bug above

**Comment by grandinj** [comment]
[perf.zip](https://github.com/KDAB/hotspot/files/2781794/perf.zip)

Attaching zipped copy of
    perf script --show-mmap-events

**Comment by grandinj** [comment]
Just checked with current master - it looks like hotspot is not successfully loading any data at all.

Anything I can do to help with this?

**Comment by milianw** [comment]
hey @grandinj, did you use the appimage from the continuous build or did you compile it all yourself? how did you record the perf data?

**Comment by grandinj** [comment]
I'm building it myself, and I recorded the data with something like:

   perf record --call-graph dwarf,32768 ./instdir/program/soffice

the code I'm profiling is built with 
   gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
on Fedora 29.

I can make debugging changes to hotspot if need be, and I hang out on IRC in the libreoffice-dev channel on freenode, and I'm around between 8am and 5pm (GMT+2 time)

**Comment by milianw** [comment]
OK, I'll try to catch you on freenode and try to figure out what's going on for you. The fact that it's completely broken for you is worrisome and strange, considering it works well for me and apparently others too...

**Comment by grandinj** [comment]
The logo on the LibreOffice conference t-shirt once read

"Proudly breaking your toolchain since 1985"

:-)

**Comment by grandinj** [comment]
with Fedora30 and latest hotspot, seems to be fine now
