### ISSUE TITLE
Flame graph, bottom up and top down show ?? as method names

### ISSUE THREAD

**Issue by PanderMusubi** [KDAB/hotspot#169]
This took a while to figure out. The flame graph, bottom up and top down show `??` as method names on Ubuntu 18.10 with hotspot-v1.1.0-x86_64.AppImage but not with Hotspot-git.9f70b9f-x86_64.AppImage. On Ubuntu 18.04, the method names are shown okay for both versions of hotspot.

Also the formatting of warnings written to the command line differs between hotspot-v1.1.0-x86_64.AppImage and Hotspot-git.9f70b9f-x86_64.AppImage for 18.10. Both versions report on 18.10 and 18.04 `Failed to find ELF file for an instruction pointer address. ...` and `... is missing (some) debug symbols.`

When trying to fix the `??` in the method names in the flame graph. bottom up and top down, I focused on the those and the exact `perf` command arguments, but these had nothing to do with the warnings. It was a combination of Ubuntu 18.10 and hotspot 1.1.0.

Hopefully, this helps others and that a new official version of hotspot can be released for 18.10.

( related are https://github.com/KDAB/hotspot/issues/128 and https://github.com/KDAB/hotspot/issues/123 )

**Comment by milianw** [comment]
yes, I need to release a new stable version - sorry for the delay. for now, please use the latest continuous appimage
