### ISSUE TITLE
Command line arguments not reflected in GUI

### ISSUE THREAD

**Issue by erijo** [KDAB/hotspot#171]
Values set with e.g. `--sysroot` and `--debugPaths` are not shown in the open file settings in the GUI.

Also, last time I tried with `--sysroot` it didn't work with a relative path. I had to provide the full path to get it to work. Haven't tested this with the latest version so I might have been fixed.

**Comment by milianw** [comment]
please report a separate issue for the relative paths in sysroot

**Comment by erijo** [comment]
> please report a separate issue for the relative paths in sysroot

Will do so once I have verified that it's actually a real problem. Need to test it at work...

**Comment by erijo** [comment]
> please report a separate issue for the relative paths in sysroot

See #174.
