### ISSUE TITLE
No information about CPU architecture found

### ISSUE THREAD

**Issue by kpopv** [KDAB/hotspot#176]
Following the [embedded workflow](https://github.com/KDAB/hotspot/#embedded-systems), I've gathered data on 'ls' on an 32-bit x86 system with both _perf version 3.13.11.8_ (from linux-tools package bundled with Ubuntu 14.04) and a custom build _perf version 5.1.rc1.gbabf09_. However, hotspot fails to open the resulting [perf.data](https://we.tl/t-vjFTTMXo0D ) file in both cases:

> ../hotspot-v1.1.0-x86_64.AppImage --sysroot my-sysroot/ --kallsyms my-kallsyms --appPath . --arch x86 perf.data
feature not properly read PerfHeader::Feature(CPU_TOPOLOGY) 228 212
No information about CPU architecture found. Cannot unwind.
"The hotspot-perfparser binary exited with code 6 (invalid perf data file)."

Looking at the code, it appears this _--arch x86_ should be sufficient to specify the architecture?

**Comment by milianw** [comment]
can you supply the perf.data file please?

**Comment by kpopv** [comment]
[This is the resulting perf.data file](https://file.io/vbhyT0) for _perf version 5.1.rc1.gbabf09_.

**Comment by milianw** [comment]
I don't get that error. Are you using the latest version of hotspot? if not, please try the latest continuous build appimage and check again.

Generally, `--arch` shouldn't be required, the `perf.data` file contains that information internally and we should be able to detect it automatically. It seems to work fine for me!

**Comment by kpopv** [comment]
While this perf.data file does not open with the Hotspot v1.1.0, it does with the continuous build Hotspot git 0626849.
