### ISSUE TITLE
Lots of "unhandled event type 5" (and 6) (PERF_RECORD_{UN,}THROTTLE)

### ISSUE THREAD

**Issue by cbiesinger** [KDAB/hotspot#177]
I just tried hotspot on a recorded perf run I just made, and I got lots of messages like:
unhandled event type 6
unhandled event type 5
unhandled event type 6

Perf command line was:
perf record -g -F max chrome --single-process foo.html

**Comment by cbiesinger** [comment]
perf.data: https://drive.google.com/file/d/1jiI75eDLBCPPyU1gA_B9uZR1lbO3A1yf/view?usp=sharing

**Comment by cbiesinger** [comment]
hotspot version 0626849746af5ad0c8d3bca715c64122914e09bc

**Comment by milianw** [comment]
https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/perf_event.h#L786

interesting! I've never seen these events myself! looking at how it's used in the kernel, this undocumented event seems to occur when the perf events gets throttled, cf. https://elixir.bootlin.com/linux/latest/source/kernel/events/core.c#L2268

how do you think should we handle this in hotspot - just ignore it? That seems to be what perf record/script is doing.

Anyhow, one way or another, you can safely ignore this warning for now.
