### ISSUE TITLE
Loading a trace is much slower in 1.2 than in 1.1

### ISSUE THREAD

**Issue by jcelerier** [KDAB/hotspot#192]
I recorded a trace doing the same actions with 1.1 and 1.2 - loading it takes roughly five seconds with 1.1, while it's been a it for a few minutes for 1.2 and is only at 10%.

The trace is relatively large (700 megabytes).

**Comment by milianw** [comment]
recording (i.e. running perf) or analyzing (i.e. running hotspot / hotspot-perfparser) is slower?

you should only need to record once and then analyze the same data file - do you still see the performance degradation?

Please share the file with me (either here publically, or through private means) - please also include the dependent DSOs. i.e. do something like this:

```
perf archive
tar -cjvf perf_data_and_symbols.tar.bz2 perf.data.tar.bz2 perf.data
```

then send me `perf_data_and_symbols.tar.bz2`

**Comment by jcelerier** [comment]
just investigated this further and it turns out that the trace generated with 1.1 was missing a lot of symbols for some reason which made it faster to load, but also less useful. Sorry for the noise !

**Comment by milianw** [comment]
reopening, as there are situations where perfparser is excruciatingly slow - also was reported by someone trying to profile firefox
