### ISSUE TITLE
Battery charge graph similar to Battery Historian

### ISSUE THREAD

**Issue by vlisivka** [KDAB/hotspot#196]
I need to debug power consumption issues on armv7 device with Yocto Linux. It looks like Hotspot is perfect tool for the job except that I cannot find any way to record/present battery voltage or/and discharge rate (`current_now`) .

Is it possible to record battery voltage or current, as presented in battery syfs directory, and then display it on a timechart graph?

**Comment by milianw** [comment]
is there a perf event for that? if so, please document how you run `perf record`. then we can think about adding visualizations for the trace data.

**Comment by milianw** [comment]
no response until now, so closing this - if you have a clear outline that shows how this could be implemented, please reopen
