### ISSUE TITLE
Perfparser exits with code 1 (TCP Socket error) when opening a perf.data file

### ISSUE THREAD

**Issue by JuanLuisHortelano** [KDAB/hotspot#197]
**Bug description**
When opening a perf.data file from gui Hotspot outputs the following error:
"The hotspot-perfparser binary exited with code 1 (TCP socket error)."
Upon restarting the program it loads the perf.data file just fine

**To Reproduce**
1. Download hotspot-v1.2.0-x86_64.AppImage
2. Create a perf.data file from terminal or using the Hotspot record data function
3. Open file from GUI
4. Error appears
5. Restart Hotspot to load perf.data file correctly

**Screenshot**
![Screenshot_20190604_114058](https://user-images.githubusercontent.com/14986892/58869337-53d6b900-86be-11e9-9672-1d1dc97697f5.png)

**Version Info:**
 - Linux Kernel version: 4.15.0-50-generic
 - perf version: 4.15.18
 - hotspot version: hotspot-v1.2.0-x86_64.AppImage

**Comment by milianw** [comment]
can you attach such a `perf.data` file that produces the issue? or are you saying that restarting hotspot "fixes" the load? Does this mean that loading the first `perf.data` works, but a second one fails?  I've never seen this, so I'm really wondering what's going on here

**Comment by adamnovak** [comment]
I have the same issue.

It looks like the appimage is managing to look outside itself, on my actual system, for Qt 5.10, but my system (Ubuntu 18.04) only has 5.9 available:

```
[anovak@hex ~]$ ~/bin/hotspot-v1.2.0-x86_64.AppImage 
/tmp/.mount_hotspolV4MzD/opt/lib/x86_64-linux-gnu/libexec/hotspot-perfparser: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by /tmp/.mount_hotspolV4MzD/opt/lib/x86_64-linux-gnu/libexec/hotspot-perfparser)
"The hotspot-perfparser binary exited with code 1 (TCP socket error)."
[anovak@hex ~]$ uname -a
Linux hex 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[anovak@hex ~]$ ls /usr/lib/x86_64-linux-gnu/libQt5Core*
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.5
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9
[anovak@hex ~]$ 
```

**Comment by milianw** [comment]
ah, that's a packaging bug in the AppImage then. Thanks, I'll try to reproduce and investigate that issue.

**Comment by milianw** [comment]
Please try the continous build package for the patch above, it should be ready in a few minutes I hope

**Comment by milianw** [comment]
https://github.com/KDAB/hotspot/releases/tag/continuous should help now, I hope - please verify that it's actually fixed

**Comment by milianw** [comment]
I'm assuming it got fixed, if not please chime in

**Comment by josephrocca** [comment]
@milianw I get this error on Ubuntu 18.04 using the `v1.2.0` AppImage release:

```
/tmp/.mount_hotspo5FHjdd/opt/lib/x86_64-linux-gnu/libexec/hotspot-perfparser: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by /tmp/.mount_hotspo5FHjdd/opt/lib/x86_64-linux-gnu/libexec/hotspot-perfparser)
"The hotspot-perfparser binary exited with code 1 (TCP socket error)."
```
It happens when I try to load a `perf.data` file that I've recorded manually (using the command specified on [the 1.2.0 release page](https://github.com/KDAB/hotspot/releases/tag/v1.2.0)), and it also happens when I click the "view results" button after recording an execution using the GUI. But weirdly, if I close the program (after getting the error) and then open it up again, it immediately loads the results page for the previously-recorded perf.data :S

**Comment by milianw** [comment]
you probably mean #202, but yes - just use the continuous build for now to workaround this issue @josephrocca

**Comment by josephrocca** [comment]
Yep, continuous build works a treat - thanks for this great software!
