### ISSUE TITLE
cmake failure in perfparser

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#201]
with current master, on Fedora 30, I get:

-- Configuring done
CMake Error at 3rdparty/perfparser.cmake:67 (add_executable):
  Cannot find source file:

    perfparser/tests/manual/perf2text/perf2text.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  3rdparty/CMakeLists.txt:1 (include)

**Comment by milianw** [comment]
you are missing a call to `git submodule update`

**Comment by grandinj** [comment]
thanks!
