### ISSUE TITLE
Flame graph not centered on first view

### ISSUE THREAD

**Issue by erijo** [KDAB/hotspot#214]
**Describe the bug**
The flame graph isn't centered as it should be the first time it is viewed.

**To Reproduce**
1. Start hotspot.
2. Go directly to the Flame Graph tab.

If one, before going to the Flame Graph tab, opens any of the other tabs, or disables the timeline (Ctrl+T), then the flame graph looks as it should on load. It is also centered if the mouse pointer is moved over the graph.

**Expected behavior**
That the flame graph is centered as usual.

**Screenshots**
![hotspot](https://user-images.githubusercontent.com/470580/65827629-75be0200-e292-11e9-97f3-ee94fb87ccac.png)

**Version Info (please complete the following information):**
Latest master (bc3923a772).

**Comment by milianw** [comment]
another elusive bug that I'd like to see fixed... I cannot reproduce it with your steps btw, it works fine most of the time which is why I haven't figure out a way to fix this yet. If you can reliably trigger it, could you try to look into this please?

**Comment by erijo** [comment]
Do you have any pointers on where I should start the search?

**Comment by milianw** [comment]
try in the flamegraph's event handlers, make sure that `selectItem` is called - it should happen in the branch for `event->type() == QEvent::Resize || event->type() == QEvent::Show`... Generally, just try to figure out when/how selectItem or even layoutItems is called and figure out why it goes all wrong?
