### ISSUE TITLE
Provide spackage Hotspot (and heaptrack)

### ISSUE THREAD

**Issue by david8dixon** [KDAB/hotspot#217]
Many HPC admins are moving to [spack](https://spack.io/) as a package manager. It would be really awesome to have a [spackage](https://spack.readthedocs.io/en/latest/packaging_guide.html) for hotspot (and heaptrack couldn't find an issue tracker...).

**Comment by milianw** [comment]
Hey @david8dixon, I don't see the value myself since I wouldn't be a consumer of such a package - but patches welcome! If you can write and test such a spackage, I'd be happy to integrate it into the official repo.

Cheers

**Comment by milianw** [comment]
I'll close this report as I won't work on this myself - but if anyone else wants to supply a spackage, I'd very much welcome such a contribution!
