### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by KirillLykov** [KDAB/hotspot#223]
Did anyone try to build hotspot on Mac?
The use case is to create a perf report on a remote machine and later use hotspot on Mac to have a better gui experience. 

I've tried and stucked with the dependencies `elfutils` (I suppose it is https://sourceware.org/elfutils/). It wants gcc with `__thread` support but the one I installed using Homebrew does not support it. I wonder if anyone managed to solve this problem or found a workaround.

**Comment by milianw** [comment]
you could try `_Thread_local` and see if that works? But afaik even clang should support `__thread`? Anyhow, I would like to get feedback if you managed to compile elfutils on macOS. I think the other dependencies of hotspot should be quite straight forward.

Good luck!

**Comment by KirillLykov** [comment]
Actually, gcc supports `__thread` but check inside the `elfutils-lib` configure file says that it does not. But even if I fix this thing there are others -- like it cannot find zlib (yet it is there) and so on. Might be easier to rewrite with `cmake`. It looks like `elfutils-lib` build system needs some love

**Comment by milianw** [comment]
Currently yes, you need elfutils as it's used for symbolication and unwinding - elfutils is a very crucial part of hotspot really.

**Comment by KirillLykov** [comment]
There were some updates regarding elfutils on mac -- https://github.com/kdab-hotspot/elfutils. Basically, Dmitry made it work. Now the problem is KDE on Mac :-)
