### ISSUE TITLE
Build failure on Linux Mint

### ISSUE THREAD

**Issue by nickdesaulniers** [KDAB/hotspot#229]
**Describe the bug**
```sh
$ cmake .. -G Ninja      
CMake Error at CMakeLists.txt:45 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.10".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.9.5
```

**To Reproduce**
Following the readme for debian based systems.

**Version Info (please complete the following information):**

Linux Mint 19.3

It seems that the newest release of qt5 my distro packages is qt5.9.5. Is 5.10 strictly required?

**Comment by nickdesaulniers** [comment]
Indeed required, looks if I manually downgrade the CMakeLists.txt, I can configure the build, but get linkage failures against various Qt functions.

**Comment by nickdesaulniers** [comment]
Further, it seems the AppImage binary release doesn't work.

`The hotspot-perfparser binary has exited with code 1 (TCP socker error)
```
/tmp/.mount_hotspoHDtyLD/opt/lib/x86_64-linux-gnu/libexec/hotspot-perfparser: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10' not found (required by /tmp/.mount_hotspoHDtyLD/opt/lib/x86_64-linux-gnu/libexec/hotspot-perfparser)
"The hotspot-perfparser binary exited with code 1 (TCP socket error)."
```

**Comment by nickdesaulniers** [comment]
cool, I was able to fetch a newer Qt from this PPA: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.14.1-bionic

It might be worthwhile to note to ubuntu/mint users that their standard qt5 is way outdated.

**Comment by milianw** [comment]
Which AppImage did you use? The latest continuous build?

**Comment by milianw** [comment]
Without any information, I cannot help you - please reopen and provide the missing information then. The AppImage attached to the Continous build should work.
