### ISSUE TITLE
enable rust demangling for appimages

### ISSUE THREAD

**Issue by milianw** [KDAB/hotspot#239]
as the title says

**Comment by milianw** [comment]
@Marwes hey could you test the latest appimage (in the Continuous tag) and see if it works for you with rust demangling? In my simple testing it seems to have worked...

**Comment by Marwes** [comment]
![Screenshot from 2020-05-17 15-00-42](https://user-images.githubusercontent.com/957312/82147334-4ffc6200-984f-11ea-9468-e654a2d0e840.png)

Looks great! Will let you know if I find any issues.

**Comment by milianw** [comment]
perfect, thanks for the feedback!
