### ISSUE TITLE
Does not demangle D programming language names

### ISSUE THREAD

**Issue by baryluk** [KDAB/hotspot#242]
`_D3std6random201__T7uniformVAyaa2_5b29TiTiTS3std6random135__T21MersenneTwisterEngineTkVmi32Vmi624Vmi397Vmi31Vki2567483615Vmi11Vki4294967295Vmi7Vki2636928640Vmi15Vki4022730752Vmi18Vki1812433253Z21MersenneTwisterEngineZ7uniformFNaNfiiKS3std6random135__T21MersenneTwisterEngineTkVmi32Vmi624Vmi397Vmi31Vki2567483615Vmi11Vki4294967295Vmi7Vki2636928640Vmi15Vki4022730752Vmi18Vki1812433253Z21MersenneTwisterEngineZi`

isn't supper friendly too look at :)

```
$ echo ... | c++filt  --format=dlang
std.random.uniform!("[)", int, int, std.random.MersenneTwisterEngine!(uint, 32uL, 624uL, 397uL, 31uL, 2567483615u, 11uL, 4294967295u, 7uL, 2636928640u, 15uL, 4022730752u, 18uL, 1812433253u).MersenneTwisterEngine).uniform(int, int, ref std.random.MersenneTwisterEngine!(uint, 32uL, 624uL, 397uL, 31uL, 2567483615u, 11uL, 4294967295u, 7uL, 2636928640u, 15uL, 4022730752u, 18uL, 1812433253u).MersenneTwisterEngine)
```

Is much better. Just showing an extreme example, but even for short functions it makes a difference.

I guess this also applies to the `perf-report`, but the hotspot doesn't demangle names (identifiers, functions, methods, etc), produced by D compilers (dmd, ldc, gdc).

There is a D demangler in gcc (in libiberty directory), and it is also periodically synced to binutils (`objdump`, `c++filt`, etc), (also in libiberty directory).

https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libiberty;hb=HEAD

http://sourceware.org/git/?p=binutils-gdb.git;a=tree;f=libiberty;hb=HEAD

I looked at kernel sources for perf, and it looks like linux perf is using own demangler (not libiberty) https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/util?h=v5.7

Would it be possible maybe to use libiberty (need to check license) directly in hotspot for this? libiberty also supports few other languages (including rust).

**Comment by milianw** [comment]
we are using elfutils, not libiberty/binutils, so we would need a separate library with a liberal licence which we can link against - do you know one?

**Comment by milianw** [comment]
I see there's https://dlang.org/phobos/core_demangle.html - is there a way to call this from C/C++ - i.e. can you create a shim library in D that we can integrate easily into our CMake build system that spits out a shared library and a C API we can call from our C++ code?

**Comment by baryluk** [comment]
@milianw It is possible, in fact without the shim (one can create `extern (C)` functions directly in D language source code with full D language features), but to make it fully work (i.e. link without full D runtime library, including garbage collector), requires some modifications to the code. It requires a D runtime and GC because there are few places in this module where 1) exceptions are thrown, 2) destinations arrays are resized dynamically, and the old copies are left to GC to collect.

https://github.com/dlang/druntime/blob/master/src/core/demangle.d#L1965

https://github.com/dlang/druntime/blob/master/src/core/demangle.d#L1988

https://github.com/dlang/druntime/blob/master/src/core/demangle.d#L1981

Are the problematic lines.

Fixing 2 is easy, by instead returning null and error if the dst array is to small. That is very easy to do and I have working prototype for this.

Fixing 1 is a bit trickier.

Exceptions throwing and catching on its own are not a problem per se, but the major issue is that `Exception` type in D are allocated on heap via GC, and then throw as references, and Exceptions derive from base Exception and Object classes, so their constructors need to be technically available, but that requires a bit of runtime data available, which is provided by a special package called `object.d`, but it is provided by the compiler.

Here is an example of me compiling it with extra function with extern(C) to do internal lifting of pointers. But the calls to arrayAccumulate (probably expanded from things like `arr1 ~= arr2 ~ arr3 ~ arr4;` (which can be optimized by first computing sizes of arrays and resizing arr1 only once, instead 3 times), and few other D runtime stuff remains.

'U' are unknown symbols provided by other stuff expected to be present in D programs.

Compiled with ldc compiler:

```
$ nm demangle.o | grep ' U '
                 U _D10TypeInfo_b6__initZ
                 U _D10TypeInfo_i6__initZ
                 U _D10TypeInfo_l6__initZ
                 U _D10TypeInfo_m6__initZ
                 U _D11TypeInfo_Aa6__initZ
                 U _D12TypeInfo_Axa6__initZ
                 U _D13TypeInfo_Enum6__vtblZ
                 U _D14TypeInfo_Class6__vtblZ
                 U _D14TypeInfo_Const6__vtblZ
                 U _D15TypeInfo_Struct6__vtblZ
                 U _D4core8internal5array5utils11gcStatsPureFNaNbZSQBu6memory2GC5Stats
                 U _D4core8internal5array5utils12__ModuleInfoZ
                 U _D4core8internal5array5utils14accumulatePureFNaNbAyaiQeQgmZm
                 U _D6object6Object5opCmpMFCQqZi
                 U _D6object6Object6toHashMFNbNeZm
                 U _D6object6Object8opEqualsMFCQtZb
                 U _D6object9Exception6__ctorMFNaNbNiNfAyaQdmCQBp9ThrowableZCQBx
                 U _D6object9Throwable4nextMFNaNbNdNiNlNfCQBlQBhZv
                 U _D6object9Throwable4nextMNgFNaNbNdNiNjNfZNgCQBqQBm
                 U _D6object9Throwable7__ClassZ
                 U _D6object9Throwable7messageMxFZAxa
                 U _D6object9Throwable7opApplyMFMDFCQBfQBbZiZi
                 U _D6object9Throwable8toStringMFZAya
                 U _D6object9Throwable8toStringMxFMDFxAaZvZv
                 U _D9Exception7__ClassZ
                 U _d_allocclass
                 U _d_allocmemory
                 U _d_arraybounds
                 U _d_arraysetlengthiT
                 U _d_array_slice_copy
                 U _d_assert
                 U _d_dso_registry
                 U _d_eh_enter_catch
                 U _d_eh_personality
                 U _d_throw_exception
                 U __errno_location
                 U memcmp
                 U memset
                 U snprintf
                 U __start___minfo
                 U __stop___minfo
                 U strtold
                 U _Unwind_Resume
```

Compiled with gdc compiler (and `-nophoboslib -fno-exceptions -fno-moduleinfo`, but with `-frtti`):

```
                 U _D10TypeInfo_b6__initZ
                 U _D10TypeInfo_i6__initZ
                 U _D10TypeInfo_m6__initZ
                 U _D11TypeInfo_Aa6__initZ
                 U _D12TypeInfo_Axa6__initZ
                 U _D13TypeInfo_Enum6__vtblZ
                 U _D14TypeInfo_Class6__vtblZ
                 U _D14TypeInfo_Const6__vtblZ
                 U _D15TypeInfo_Struct6__vtblZ
                 U _D4core8internal6string20unsignedToTempStringFNaNbNiNfmMNkAakZAa
                 U _D6object6Object5opCmpMFC6ObjectZi
                 U _D6object6Object6toHashMFNbNeZm
                 U _D6object6Object8opEqualsMFC6ObjectZb
                 U _D6object9Exception6__ctorMFNaNbNiNfAyaAyamC6object9ThrowableZC9Exception
                 U _D6object9Throwable8toStringMFZAya
                 U _D6object9Throwable8toStringMxFMDFxAaZvZv
                 U _D9Exception7__ClassZ
                 U _d_allocmemory
                 U _d_arraybounds
                 U _d_arraycopy
                 U _d_arraysetlengthiT
                 U _d_assert
                 U _d_assert_msg
                 U _d_throw
                 U __errno_location
                 U _GLOBAL_OFFSET_TABLE_
                 U memcmp
                 U snprintf
                 U strtold
```

Again mostly because of exceptions.

The best option would be to rewrite this code to not use exceptions for communication of overflows, and instead return the errors and or set flags for that.  Then it will be trivial to compile it to directly C callable code with no problems at all and no D runtime (`dmd -betterC`, or `gdc -fno-runtime`).

**Comment by baryluk** [comment]
@WalterBright Hi Walter, would it make sense to make `core.demangle` (at least the demangling part, and protect the mangler by the `version` block) be fully `@nogc` and `@nothrow` and not use internally exceptions and rtti, and maybe even not call any other modules.

I know it uses `core.checkedint`, for `mulu` and `addu`, in `core.demangle.Demangle!().decodeNumber`, and uses `core.internal.string : UnsignedStringBug, unsignedToTempString` in `core.demangle.Demangle!().putAsHex` functions.

I think it is important for D programming language to see better support in various tools related to performance, profiling and debugging, and having easier access to reference demangler from C, and C++, would be really good.

**Comment by WalterBright** [comment]
It would be best to file a D bugzilla issue for this.
