### ISSUE TITLE
Privilege elevation fails with no useful log

### ISSUE THREAD

**Issue by novakboskov** [KDAB/hotspot#244]
**Describe the bug**
I click record. `kdesu` appears, accepts the password, GUI freezes.

**To Reproduce**
1. click record

**Expected behavior**
Why don't you guys just first check whether the app is run with `sudo`? Wouldn't that be the simplest possible solution? `kdesu` is deprecated for security reasons either way.

**Version Info (please complete the following information):**
 - Linux Kernel version: Ubuntu 18.04
 - perf version: 4.15.18
 - hotspot version (appimage? selfcompiled?): appimage

**Comment by milianw** [comment]
running a graphical app with sudo isn't better either

what version of the appimage did you use? the latest continuous appimage or the latest "stable" version?

**Comment by milianw** [comment]
I've recently added `pkexec` as an alternative - that should hopefully work for you now. if not, please reopen this issue with more information on how to reproduce this (and what version of the app was used).
