### ISSUE TITLE
toggle for flame graph

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#246]
Context: I have quite a lot of threads and processes I'm looking at, and often one thread is blocked because of some other threads' actions.

So I'd like to get a better/larger view of the action.

But I can't make the window any bigger, nor the Timeline any bigger.

So what would perhaps be nice is a toggle to turn off the flame-graph, the same way the Timeline can be turned on and off.

Thanks

**Comment by milianw** [comment]
yep, agreed. and I should also try to integrate KDDockWidgets to make the whole view setup much more flexible

**Comment by milianw** [comment]
this is now implemented in master

**Comment by grandinj** [comment]
thanks!
