### ISSUE TITLE
Less restrictive window size limits

### ISSUE THREAD

**Issue by thehans** [KDAB/hotspot#247]
**Is your feature request related to a problem? Please describe.**
I want to compare two builds of a single application by viewing their flame graphs stacked on top of each other.
I am able to tile two instances of Hotspot vertically(side-by-side) on my 1920x1080 display, and my window manager automatically snaps them into position, but it refuses to tile in the other direction because of seemingly arbitrary window height limits which are larger than half the screen height (minus a horizontal panel for my DE: Cinnamon on Linux Mint 20).  

I have hidden the timeline view, so just flame graph is shown, but it does not affect the minimum window size, and even more strangely, I had different minimum height on one Hotspot instance vs another.  
I was able to track this down to the fact that one had recorded with the "Advanced" settings expanded while the other had not.

**Describe the solution you'd like**
After switching to "View Results", the window height should not be limited to the size of the "Record data" view.

**Describe alternatives you've considered**
Additionally or alternatively, make the "Record data" screen into a scrollable area, since it seems to be the limiting factor for window height.

**Additional context**
A screenshot showing the minimum height I was able to set with "Advanced" settings expaneded vs not expanded:
![Screenshot from 2020-07-23 18-08-27](https://user-images.githubusercontent.com/252233/88347257-f82b1d00-cd0f-11ea-97f4-e56a42d8021c.png)

Somewhat related to #235 or #37, since tiling windows could be considered at least one way to workaround for lack of those features existing, but as it is I can't even tile properly.

**Comment by milianw** [comment]
the best solution to this would be to find a way to convince the stacked widget to ignore the size constraints of invisible pages, such that the min/max size of the record page doesn't influence the min/max size of the report view
