### ISSUE TITLE
AppImage fails to analyze:  `GLIBC_2.18' not found (required by /tmp/.mount_HotspoRWNh3k/usr/lib/librustc_demangle.so)

### ISSUE THREAD

**Issue by lferraro** [KDAB/hotspot#250]
**Describe the bug**
When loading a perf.log file the application pops an error saying: 
The hotspot-perfparser binary exited with code 1 (TCP socket error)

A similar behaviour has  been previously reported in #197 

**To Reproduce**
1. create a perf.log of an application with perf
2. load the file into the hotspot application
3. see the error :-)

$> ./Hotspot-git.12a5de0-x86_64.AppImage
/tmp/.mount_HotspoRWNh3k/usr/lib/x86_64-linux-gnu/libexec/hotspot-perfparser: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/.mount_HotspoRWNh3k/usr/lib/librustc_demangle.so)
"The hotspot-perfparser binary exited with code 1 (TCP socket error)."

**Version Info (please complete the following information):**
 - Linux Kernel version: CentOS Linux release 7.6.1810 (Core) kernel 3.10.0-957.27.2.el7.x86_64
 - perf version: perf version 3.10.0-957.27.2.el7.x86_64.debug
 - hotspot version: ./Hotspot-git.12a5de0-x86_64.AppImage

**Comment by milianw** [comment]
Ouch, seems like rustc_demangle pulls in a glibc symbol that's incompatible with the CentOS version you have... Not sure when I find the time to investigate this in more detail

**Comment by lferraro** [comment]
> Ouch, seems like rustc_demangle pulls in a glibc symbol that's incompatible with the CentOS version you have... Not sure when I find the time to investigate this in more detail

Do you think is there any work around for that? 

For example, we use [module ](http://modules.sourceforge.net/) to load other software and set the proper environment in a terminal.

**Comment by milianw** [comment]
the quickest workaround will be to disable the rustc demangling support - I'll create you an appimage for that

but a proper solution will require more time to investigate this problem

**Comment by milianw** [comment]
Try this one (but note that rustc demangling is disabled): https://github.com/KDAB/hotspot/releases/download/v1.3.0/hotspot-v1.3.0-x86_64-NoRustDemanglingForCentOS7.AppImage

**Comment by lferraro** [comment]
> Try this one (but note that rustc demangling is disabled): https://github.com/KDAB/hotspot/releases/download/v1.3.0/hotspot-v1.3.0-x86_64-NoRustDemanglingForCentOS7.AppImage

Milian, this version works! Thank you for your work. I'm now able to launch and test performances on this cluster.

Do you think this working configuration can be mantained in future AppImage or could break other host platforms?

**Comment by GitMensch** [comment]
Can you add this special version to the upcoming releases please?

**Comment by GitMensch** [comment]
Just a note to answer my own question: the delay-load of the plugin with a fallback to "plugin not available" should solve this issue without a special AppImage. Everything we need to do is to wait on the new release (if someone has a pointer where to look at a rough plan: please share).

**Comment by milianw** [comment]
I've just uploaded a new appimage to https://github.com/KDAB/hotspot/releases/tag/continuous - but it does not ship with the rust demangler. I'll have to look at building that in my docker env.
