### ISSUE TITLE
Features: Disassembler, Cross-platform Disassembler, Cross-profiling settings dialog

### ISSUE THREAD

**Issue by dknysh** [KDAB/hotspot#253]
Hello,
We are the NIPS team (http://nips.ru).
Our team has developed some new features for Hotspot.
These are mostly new component Disassembler (+ Cross-platform Disassembler for ARMv7, ARMv8) to generate and output
Disassembly with costs for selected functions/methods, improved UI to Cross-profiling settings and some more.
I will send merge requests for the changes.

![image](https://user-images.githubusercontent.com/60460656/93461152-0438f280-f8ed-11ea-8dac-a575c88ca4e7.png)
![image](https://user-images.githubusercontent.com/60460656/93461165-0d29c400-f8ed-11ea-99fa-900caf0675e4.png)

**Comment by milianw** [comment]
please split this into parts - one for the disassembler, one for the cross-platform settings

**Comment by milianw** [comment]
I think this is done now
