### ISSUE TITLE
perf 5.4.55 record "-z" key is not yet supported (despite being mentioned in help output)

### ISSUE THREAD

**Issue by dmikushin** [KDAB/hotspot#256]
**Describe the bug**
perf record "-z" key is no longer supported

**To Reproduce**
Run hotspot AppImage on Ubuntu 20.04

**Screenshots**
```
perf record -o /home/.../perf.data --call-graph dwarf --aio -z --sample-cpu /home/.../venv/bin/python3 ./example.py
  Error: unknown switch `z'
```
**Version Info (please complete the following information):**
 - Linux Kernel version: 5.4.0-45-generic
 - perf version: 5.4.55
 - hotspot version (appimage? selfcompiled?): AppImage newest

**Comment by milianw** [comment]
Hey? What version of perf is this? What is the output of `perf help record`? Most notably does this contain this line:

```
       -z, --compression-level[=n]
           Produce compressed trace using specified level n (default: 1 - fastest compression, 22 - smallest trace)
```

**Comment by qarmin** [comment]
I have also same error in GUI in Ubuntu 20.04 with `perf version 5.4.60`

Strange, but when running `perf help record` there is identical as yours line about compression level.

On this site I can't find `-z` flag - https://linux.die.net/man/1/perf-record

**Comment by milianw** [comment]
We will need a better way to do feature detection for perf. But that requires improvements upstream. For now, just disable compression in the Advanced settings of the record page in hotspot. That should fix this issue.

**Comment by thehans** [comment]
I have been disabling compression whenever I run Hotspot, but it does not seem to remember preferences for this setting like it does with all others on the record screen.

Please save this preference so its not required to manually disable each time.

**Comment by milianw** [comment]
@thehans thanks for the report, that was indeed broken, but is now fixed :)

I've also written a question to perf upstream to ask for a better way to do such feature detections.

**Comment by milianw** [comment]
can someone who's affected by this on Ubuntu or similar platforms please paste me this output:

```
perf version --build-options
```

most notably, does it have anything to say about aio / zstd?

thanks

**Comment by dmikushin** [comment]
```
$ perf version --build-options
perf version --build-options
perf version 5.4.55
                 dwarf: [ on  ]  # HAVE_DWARF_SUPPORT
    dwarf_getlocations: [ on  ]  # HAVE_DWARF_GETLOCATIONS_SUPPORT
                 glibc: [ on  ]  # HAVE_GLIBC_SUPPORT
                  gtk2: [ OFF ]  # HAVE_GTK2_SUPPORT
         syscall_table: [ on  ]  # HAVE_SYSCALL_TABLE_SUPPORT
                libbfd: [ OFF ]  # HAVE_LIBBFD_SUPPORT
                libelf: [ on  ]  # HAVE_LIBELF_SUPPORT
               libnuma: [ on  ]  # HAVE_LIBNUMA_SUPPORT
numa_num_possible_cpus: [ on  ]  # HAVE_LIBNUMA_SUPPORT
               libperl: [ OFF ]  # HAVE_LIBPERL_SUPPORT
             libpython: [ OFF ]  # HAVE_LIBPYTHON_SUPPORT
              libslang: [ on  ]  # HAVE_SLANG_SUPPORT
             libcrypto: [ on  ]  # HAVE_LIBCRYPTO_SUPPORT
             libunwind: [ on  ]  # HAVE_LIBUNWIND_SUPPORT
    libdw-dwarf-unwind: [ on  ]  # HAVE_DWARF_SUPPORT
                  zlib: [ on  ]  # HAVE_ZLIB_SUPPORT
                  lzma: [ on  ]  # HAVE_LZMA_SUPPORT
             get_cpuid: [ on  ]  # HAVE_AUXTRACE_SUPPORT
                   bpf: [ on  ]  # HAVE_LIBBPF_SUPPORT
                   aio: [ on  ]  # HAVE_AIO_SUPPORT
                  zstd: [ OFF ]  # HAVE_ZSTD_SUPPORT
```

**Comment by milianw** [comment]
thanks, should now be properly auto-detected in master

cheers

**Comment by qarmin** [comment]
Sadly code doesn't compile properly and CI doesn't create AppImage file
https://travis-ci.org/github/KDAB/hotspot/builds/736441592?utm_source=github_status&utm_medium=notification

**Comment by milianw** [comment]
dang, I'll have to fix the appimage scripts to use a different distro, that ubuntu is just far too old by now - I'll report a different issue for that and track it there then
