### ISSUE TITLE
build problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by fmros** [KDAB/hotspot#259]
I am not able to build hotspot on Ubuntu 18.04. 

The error:
```
$cmake ../hotspot
CMake Error at CMakeLists.txt:49 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.10".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.9.5

-- Configuring incomplete, errors occurred!
See also "/home/lab/Programs/build-hotspot/CMakeFiles/CMakeOutput.log".
```
I followed the guide in the ReadMe for Ubuntu and the section for `Build Hotsport istelf`
I tried to install qt >5.9 by hand: e.g. http://download.qt.io/official_releases/qt/5.12/5.12.9/ following this: https://wiki.qt.io/Install_Qt_5_on_Ubuntu ,  but have still the same error when trying to compile hotspot.

5.10 is not available on QT webpage any more.

Thank you.

**Comment by milianw** [comment]
Anything newer than 5.10 is supported. Alternatively use the AppImage if you don't want to install a newer Qt.
