### ISSUE TITLE
fix automatic AppImage generation

### ISSUE THREAD

**Issue by milianw** [KDAB/hotspot#264]
update the travis.ci scripts to use a different distro, probably some centos with a newer devtools. we definitely need C++14, but ideally would be able to use C++17.

**Comment by milianw** [comment]
Relates-To: https://github.com/KDAB/hotspot/issues/256

**Comment by raphinesse** [comment]
I tried to rebase the Docker-based AppImage build to Xenial. Unfortunately that seems to be a dead end. To cite the description of [Stephan Binner's Qt 5.15 PPA](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.0-xenial): 

> No SSL support as the minimum supported version of OpenSSL is 1.1 for Qt 5.15 and Xenial's is too old.

This breaks the build during linking because many `libKF5*.so`s rely on it.

**Comment by milianw** [comment]
https://invent.kde.org/mwolff/kf5-appimage-centos7 contains the setup I use to manually build appimages on Centos 7 now. https://github.com/KDAB/hotspot/releases/tag/continuous contains a fresh appimage I just build today.

Can you check if that works for you?

Otherwise,

**Comment by milianw** [comment]
@vfjerlkj can we see the build scripts for that? Most notably, I wonder if you included xcb, freetype and all these other lowlevel libraries as well? what compatibility does your binary give - i.e. can it run on RHEL 7?

**Comment by vfjerlkj** [comment]
> @vfjerlkj can we see the build scripts for that? Most notably, I wonder if you included xcb, freetype and all these other lowlevel libraries as well? what compatibility does your binary give - i.e. can it run on RHEL 7?

The only dependency is glibc >= 2.17. Of cause perf need to be installed by hand.
