### ISSUE TITLE
Dark mode is undocumented

### ISSUE THREAD

**Issue by NAThompson** [KDAB/hotspot#266]
**Describe the bug**

It appears that Hotspot has a dark mode, from (say) [this screenshot](https://raw.githubusercontent.com/KDAB/hotspot/master/screenshots/off-cpu.png).

However, I cannot find out how to enable it.

**To Reproduce**

I used the latest [AppImage](https://github.com/KDAB/hotspot/releases/tag/continuous) on Ubuntu 18.04.

**Expected behavior**

An option in Settings to enable a dark mode.

**Version Info:**

```
$ uname -r
5.4.0-51-generic
$ perf -v
perf version 5.4.g219d54332a09
```

I used the latest [AppImage](https://github.com/KDAB/hotspot/releases/tag/continuous) on Ubuntu 18.04.

**Comment by milianw** [comment]
it just picks up the system colors, it's not a per-app setting
