### ISSUE TITLE
Install desktop and appdata files system-wide for Linux packaging

### ISSUE THREAD

**Issue by akien-mga** [KDAB/hotspot#268]
**Is your feature request related to a problem? Please describe.**
I'm packaging Hotspot for a Linux distribution, Mageia.

**Describe the solution you'd like**
The hotspot release tarballs (at least as of `v1.3.0`) provide `hotspot.desktop` and `com.kdab.Hotspot.appdata.xml`, but those are not installed system-wide when calling `make install`.

They should go in:
```
CMAKE_INSTALL_DATAROOTDIR/applications/hotspot.desktop
CMAKE_INSTALL_DATAROOTDIR/metainfo/com.kdab.Hotspot.appdata.xml
```

On the other hand the icon files needed for the `.desktop` file are currently installed properly as
```
CMAKE_INSTALL_DATAROOTDIR/icons/hicolor/*/apps/hotspot.png
```

**Describe alternatives you've considered**
They can be installed manually, but chances are that some packagers would forget to do it, as seen in the Fedora and Arch Linux packages:

https://src.fedoraproject.org/rpms/hotspot/blob/master/f/hotspot.spec
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hotspot

**Additional context**
I could possibly make a PR but:
- I'm not a CMake guru and much less experienced with KF5/ECM specifics, so I'm not sure I'd find the *right* way to do it.
- Similarly, I'm not familiar with the interactions between ECM and AppImage generation, and I wouldn't want the system install specific changes break AppImage generation.

**Comment by milianw** [comment]
I've pushed a change to install the files to both the 1.3 branch and current master - can you please try and confirm it works?

thank you
