### ISSUE TITLE
Enable rustc demangling at runtime rather than compile time

### ISSUE THREAD

**Issue by krtab** [KDAB/hotspot#269]
Hi,
Thanks a lot for your work on hotspot ! I have a feature proposition regarding rustc-demangling:

**Is your feature request related to a problem? Please describe.**
When packaging hotspot, it is currently up to the packager to decide wether or not to compile with rust demangling support or not. Given that compiling with rust demangling transitively means depending on cargo, the tradeoff is not easy to decide.

**Describe the solution you'd like**
It would be nice to determine at runtime if the rustc_demangle.so is present, and transparently provide rust demangling if it it the case. Packaging wise that would mean that the hotspot package would have an optional dependency on rustc-demangle, and that simply installing "rustc-demangle" would enable rustc-demangling.
I'm no C++ coder, but I guess the solution would use `dlopen`, as outlined here for example: <https://hackaday.com/2018/07/12/its-all-in-the-libs-building-a-plugin-system-using-dynamic-loading/>

**Describe alternatives you've considered**
Currently, the choice must be made at compile-time and hence a package only presents one of the two options.

**Comment by milianw** [comment]
that's a really good idea, I'll see if I can implement this over the next days

**Comment by milianw** [comment]
Actually, the more I think about it, the less I think this would actually improve anything?

Note that cargo would essentially be a compile/packaging dependency. But it's _not_ a runtime dependency as the rust library produced doesn't depend on anything rust specific:

```
$ cargo build --release
$ ldd target/release/librustc_demangle.so
        linux-vdso.so.1 (0x00007ffc87ffa000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3c73b83000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3c73b61000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3c73b47000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3c7397e000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f3c73c0d000)
```

So what would we actually gain by looking for the library at runtime? Either you have it packaged, and then you can depend on it beforehand. Or you don't have it and then just skip it?

We could obviously still use `QLibrary` to look for librustc_demangle.so manually, but I feel like this is just going to complicate the code for no real advantage?

**Comment by milianw** [comment]
it's actually not much more complicated, I'll push the change now for that though I'd still like to hear a bit more about how this simplifies things :)

**Comment by milianw** [comment]
please reopen if this doesn't work as you'd expect it to

**Comment by krtab** [comment]
Thanks a lot for working on it.

I'll test it later but I can already try to give good reasons to detect this dependency at runtime.

One way to put my train of thought is that enabling at compile-time forces distributions to have the same tier of package maintenance for hotspot and its demanglers. I'm not sure how many there are currently, but if D demangling was to be merged, that would already be two, and I guess this can only extend in the future.

I think it is reasonable to expect distribution to package hotspot one day, but I am not sure it is reasonable to expect them to package rustc, or D demangling. In any case, the distribution maintainers' choice of packaging it or not would be forced onto the users.

If you detect the various demangling "plugins" at runtime, it becomes possible for a distribution to package a vanilla hotspot, not commit to package the "plugins", but let users decide if they want to install them.

On top of that, some distributions provide only source packages (the [AUR](https://aur.archlinux.org/packages/hotspot/) for Archlinux, Nix more or less, Gentoo for sure), and on these, the end-user definitely has to pay for the whole Rust toolchain if rustc-demangling is enabled at compile time.

Let me know if some things are still unclear.

**Comment by krtab** [comment]
Good news, I got it to work!

Do you know when will the next release be so that we can update the packages in anticipation?

**Comment by GitMensch** [comment]
I _think_ one additional benefit of "at runtime" is that we can have a release package including the de-mangling part but if the packaged rustc needs a newer libc only the "module" for demangling would not be loaded but hotspot still runs (so we need no special CentOS7 package AppImage). Is that assumption correct? And yes of course I'd love a new version with that, too.
