### ISSUE TITLE
Unable to install/start on CentOS 8

### ISSUE THREAD

**Issue by tgrgin** [KDAB/hotspot#270]
**Describe the bug**
Unable to start AppImage or to install RPM from Fedora repository.

**To Reproduce**
$ chmod u+x Hotspot-git.5ca2915-x86_64.AppImage                                                                                                         
$ mv Hotspot-git.5ca2915-x86_64.AppImage hot_spot.AppImage                                                                                              
$ ./hot_spot.AppImage                                                                                                                                   
fuse: failed to exec fusermount: No such file or directory

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information open dir error: No such file or directory

$ wget http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/h/hotspot-1.3.0-1.fc34.src.rpm                 
--2020-12-17 05:26:57--  http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/h/hotspot-1.3.0-1.fc34.src.rpm                   
Resolving dl.fedoraproject.org (dl.fedoraproject.org)... 38.145.60.24, 38.145.60.22, 38.145.60.23                                                                          
Connecting to dl.fedoraproject.org (dl.fedoraproject.org)|38.145.60.24|:80... connected.                                                                                   
HTTP request sent, awaiting response... 200 OK
Length: 3330211 (3.2M) [application/x-rpm]
Saving to: ‘hotspot-1.3.0-1.fc34.src.rpm’

hotspot-1.3.0-1.fc34.src.rpm               100%[========================================================================================>]   3.18M  --.-KB/s    in 0.1s    

2020-12-17 05:26:57 (29.0 MB/s) - ‘hotspot-1.3.0-1.fc34.src.rpm’ saved [3330211/3330211]                                                                                   

$ sudo yum install hotspot-1.3.0-1.fc34.src.rpm
Last metadata expiration check: 2:50:53 ago on Thu 17 Dec 2020 02:37:47 AM EST.
Error: Will not install a source rpm package (hotspot-1.3.0-1.fc34.src).

**Expected behavior**
Being able either to start AppImage or install rpm.

**Screenshots**

**Version Info (please complete the following information):**
CentOS Linux release 8.2.2004 (Core) 
NAME="CentOS Linux"
VERSION="8 (Core)"
Linux version 4.18.0-193.19.1.el8_2.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Mon Sep 14 14:37:00 UTC 2020

**Additional context**

**Comment by milianw** [comment]
As the output tells you: Either install fuse, or run `hotspot...AppImage --appimage-extract` and then run `./squashfs-root/AppRun`.

And a source rpm is just that, a source rpm - please read up on the tools

**Comment by tgrgin** [comment]
Not always possible, this was remote host. Thank you.
