### ISSUE TITLE
Newest Linking of Flamegraph to timechart is awesome.

### ISSUE THREAD

**Issue by NAThompson** [KDAB/hotspot#278]
The newest behavior of Hotspot which links the flamegraph to the timechart is amazing:

https://user-images.githubusercontent.com/5459618/103804160-45c5e880-5017-11eb-9063-ba3d8b5c5f4e.mp4

**Comment by milianw** [comment]
cool, glad you like it. but... this is not a bug, is it? :) if so, then please clarify what it is and reopen this issue

**Comment by NAThompson** [comment]
I didn't mean to add the bug label; my bad!

Awesome product nonetheless.
