### ISSUE TITLE
Rust symbol demangling does not work from AppImage release

### ISSUE THREAD

**Issue by szarykott** [KDAB/hotspot#279]
**Describe the bug**
I am not exactly sure it is a bug, but since I found issues and release notes that rust symbol demangling is supported, I file it as a bug. As you might expect after introduction, symbol demangling does not work for me when running Hotspot from AppImage.

**To Reproduce**
1. Create a rust program 
2. Compile it with `cargo build --release` with debug info 
3. Run Hotspot from AppImage from newest release 
4. Record perf data of the compiled program (e.g .target/release.program)
5. Open recorded trace and see symbols are not demangled.

**Expected behavior**
I would expect to see symbols demangled. It is supported by perf - when I open the same trace with `perf report` symbols are properly demangled.

If this is a matter of enabling some switches during run of AppImage, in system or inside hotspot, it would be nice to see documentation improvement. (if you tell me how to enable it in such case, I'd be willing to create a PR with pretty documentation)

**Screenshots**
![obraz](https://user-images.githubusercontent.com/32487860/104815363-5135c280-5814-11eb-9a0d-0fba5e072248.png)

**Version Info (please complete the following information):**
 - Linux Kernel version: 5.4.0-47-generic (Linux Mint 20.1)
 - perf version: 5.4.55
 - hotspot version (appimage? selfcompiled?): hotspot-v1.3.0-79-gd06e376-x86_64.AppImage
 - if self-compiled hotspot, what version of elfutils:

**Comment by GitMensch** [comment]
I highly suggest to recheck with hotspot-v1.3.0-99-gdf39e78-x86_64.AppImage, rust demangling should work as long as you have the library, otherwise Hotspot will start with a message

> failed to load rustc_demangle library, rust demangling support is not available. "Cannot load library rustc_demangle: (rustc_demangle: cannot open shared object file: No such file or directory)"

**Comment by szarykott** [comment]
Thank you for the tip.

I'll try it out. I can also add a comment that I checked with latest full release at the time (non coming from nightly CI/CD or however to call it) and it worked fine.

I think the issue can be closed if it is resolved :)

**Comment by milianw** [comment]
https://github.com/KDAB/hotspot/releases/tag/continuous contains a new appimage which should come with working rust demangling - please try it out and reopen if that doesn't work

cheers
