### ISSUE TITLE
Support sampling container task

### ISSUE THREAD

**Issue by bnalkj** [KDAB/hotspot#285]
Though we can do the sampling on the host, but hotspot can't find the executable file inside container, and symbols are missing.
I noticed that perf report can show the symbols of a container task, maybe it has some way to find the executable file?

**Comment by bnalkj** [comment]
By the way, I have successfully compiled hotspot as static link executable. https://github.com/bnalkj/bnalkj/releases/download/v1.0/hotspot 
I think this is better than appimage.

**Comment by milianw** [comment]
Odd, there was a bugreport about this already (#283) but that somehow disappeared.

Anyhow, let me repeat what I wrote back then in that other report: Please provide me with simple steps to reproduce the issue. Ideally I'm looking for a simple list of steps that e.g. start some small docker container, compile some code in it, then run perf and show where/how you are loading the `perf.data` file with hotspot/perf then.

I've done perf sampling in docker in the past and managed to get hotspot working by essentially getting read access to the container filesystem from my host and then passing that as the sysroot to hotspot. If perf itself can do that automatically somehow, I'd like to try and replicate that support, but first I'd need to know what you are doing which works in perf and doesn't in hotspot.

Thanks

**Comment by milianw** [comment]
Regarding the statically linked executable, feel free to put that request into another feature request, but that has nothing to do with the problem at hand here.

**Comment by bnalkj** [comment]
I use kubernetes in fact. When I run iperf report, What I found is as below:
`pqy@ubuntu:~/static$ ps -ef|grep perf
root      38786  74076  0 17:15 pts/22   00:00:00 sudo perf report -g
root      38788  38786  0 17:15 pts/22   00:00:00 /usr/lib/linux-tools/5.3.0-64-generic/perf report -g
pqy       52732  23336  0 17:16 pts/52   00:00:00 grep --color=auto perf
pqy@ubuntu:~/static$ sudo ls -l /proc/38788/fd/
total 0
lrwx------ 1 root root 64 Mar 26 17:15 0 -> /dev/pts/22
lrwx------ 1 root root 64 Mar 26 17:15 1 -> /dev/pts/22
lr-x------ 1 root root 64 Mar 26 17:17 10 -> /mnt/huge/rtemap_0
lr-x------ 1 root root 64 Mar 26 17:17 11 -> /mnt/huge/rtemap_1
lr-x------ 1 root root 64 Mar 26 17:17 13 -> /lib/x86_64-linux-gnu/libc-2.27.so
lrwx------ 1 root root 64 Mar 26 17:15 2 -> /dev/pts/22
lr-x------ 1 root root 64 Mar 26 17:15 3 -> /home/pqy/static/perf.data
lrwx------ 1 root root 64 Mar 26 17:17 4 -> /dev/tty
lr-x------ 1 root root 64 Mar 26 17:15 5 -> /home/pqy/.debug/usr/bin/ppe/3750f6a2ab1b127aa2f86b57d0033637486c8056/elf`
Don't know who copy the executable to /home/pqy/.debug/usr/bin/ppe/3750f6a2ab1b127aa2f86b57d0033637486c8056/elf, but I have verified it md5, the same with my executable. So iperf reads the executable from /home/pqy/.debug. 
And then when I run hotspot, it can find executable as well! 
If I record a new one via hotspot GUI, then it can't find executable any more.

**Comment by bnalkj** [comment]
Further testing shows that with "--aio" can cause such problem. Without "--aio", perf will copy the exec from container to local

**Comment by bnalkj** [comment]
Not a real bug
