### ISSUE TITLE
build instructions are out of date

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#287]
(*) seem to need some kind of rust demangling thing? which I can't find a package for.

(*) needs a version of Qt that is not bundled on latest Ubuntu? Possibly drop requirement to .14 ?

(*) seems to need libzstd-dev as well now

Thanks

**Comment by milianw** [comment]
Please use the appimage if the dependencies are too hard for you to provide yourself. 

- the rust demangling stuff is optional, or should be
- Qt 5.15 is a hard requirement
- libzstd-dev should theoretically be optional too

can you please paste the actual cmake output to see if there's really a hard error or just a warning about missing optional dependencies? That said as always: patches welcome to improve things :)

**Comment by grandinj** [comment]
It just seems a little aggressive to be requiring  a Qt that is not yet available on the latest Ubuntu?

The appimage here is not up to date with HEAD?
    https://github.com/KDAB/hotspot/releases/tag/continuous
 - which is a pity, I was enjoying using and testing the latest, but building Hotspot is now becoming a bit of a pain.

cmake looks like the below:

noel@librebuild2:~/hotspot-build$ cmake ../hotspot
CMake Warning at CMakeLists.txt:63 (find_package):
  By not providing "FindLibRustcDemangle.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "LibRustcDemangle", but CMake did not find one.

  Could not find a package configuration file provided by "LibRustcDemangle"
  with any of the following names:

    LibRustcDemangleConfig.cmake
    librustcdemangle-config.cmake

  Add the installation prefix of "LibRustcDemangle" to CMAKE_PREFIX_PATH or
  set "LibRustcDemangle_DIR" to a directory containing one of the above
  files.  If "LibRustcDemangle" provides a separate development package or
  SDK, be sure it has been installed.


-- Could NOT find KDDockWidgets (missing: KDDockWidgets_DIR)
-- The following RUNTIME packages have been found:

 * objdump, Utility to generate disassembler, <https://www.gnu.org/software/binutils/>
   Support for annotating individual instructions

-- The following OPTIONAL packages have been found:

 * Zstd
 * KF5Service (required version >= 5.74.0)
 * KF5Completion (required version >= 5.74.0)
 * KF5JobWidgets (required version >= 5.74.0)
 * KF5Auth (required version >= 5.74.0)
 * KF5Codecs (required version >= 5.74.0)
 * KF5WidgetsAddons (required version >= 5.74.0)
 * KF5XmlGui (required version >= 5.74.0)

-- The following REQUIRED packages have been found:

 * Qt5Gui (required version >= 5.14.2)
 * Qt5Test
 * Qt5Svg
 * Qt5 (required version >= 5.14)
 * LibElf
 * Elfutils
 * ECM (required version >= 1.0.0)
 * Threads
 * KF5ThreadWeaver
 * Gettext
 * KF5I18n
 * KF5ItemModels
 * KF5ItemViews (required version >= 5.74.0)
 * KF5CoreAddons (required version >= 5.74.0)
 * KF5ConfigWidgets (required version >= 5.74.0)
 * Qt5Network (required version >= 5.12.0)
 * KF5KIO
 * Qt5Core (required version >= 5.12.0)
 * KF5Solid
 * KF5WindowSystem
 * KF5Notifications
 * Qt5Widgets (required version >= 5.12.0)
 * KF5IconThemes
 * KF5

-- The following RUNTIME packages have not been found:

 * LibRustcDemangle, Demangling for Rust symbols, written in Rust., <https://github.com/alexcrichton/rustc-demangle>
   Demangling of Rust symbols

-- The following REQUIRED packages have not been found:

 * KDDockWidgets
   KDDockWidgets is a Qt dock widget library written by KDAB, suitable for replacing QDockWidget and implementing
 advanced functionalities missing in Qt. https://github.com/KDAB/KDDockWidgets

CMake Error at /usr/share/cmake-3.16/Modules/FeatureSummary.cmake:457 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:93 (feature_summary)


-- Configuring incomplete, errors occurred!
See also "/home/noel/hotspot-build/CMakeFiles/CMakeOutput.log".
See also "/home/noel/hotspot-build/CMakeFiles/CMakeError.log".

**Comment by milianw** [comment]
Hmm odd, are you using the latest master? 

```
find_package(Qt5 5.15 COMPONENTS Core Widgets Network Test Svg REQUIRED)
```

So it should already depend on 5.15 here, I wonder why you still get the messages that 5.12 would be fine...

**Comment by grandinj** [comment]
> Hmm odd, are you using the latest master?

Ah, my apologies. Ubuntu ships with 5.14, so I downgraded the cmake file to 5.14 to try and get it to build. Then I bumped into the other issues, and ran out of enthusiasm.

Never mind, I'm just burned out, lately it seems like every time I try and build stuff locally I run into a chain of horrible dependencies requiring all sorts of latest stuff and crazy configurations.
Modern linux development is becoming every bit as unpleasant as developing on Windows.

**Comment by milianw** [comment]
Hoping to give you some useful tip here: Don't build stuff from source that you don't intend on working on yourself. Either rely on your package management or on appimages to consume the latest versions of software. Anything else is indeed becoming complex quite fast.

**Comment by milianw** [comment]
@FeepingCreature how did you specify the path? Generally it should be as easy as building both projects with `cmake -DCMAKE_INSTALL_PREFIX=...` and using the same prefix for both projects. Then cmake will automatically find it.

**Comment by dpelle** [comment]
@milianw wrote:

> the rust demangling stuff is optional, or should be

That is no the case for me. I'm trying to build hotspot on xunbuntu-18.04.6.
I have installed Qt 5.15.2. 
I'm trying to configure the build of hotspot but cmake fails as it cannot find LibRustcDemangle and KDDockWidgets.

This is what I see:

```
#  Get latest hotspot from github (fa3cb70c9b990f2b722cf71f178718709ceb1301 )
$ cd hotspot
$ git pull

$ cd ..
$ mkdir build-hotspot
$ cd build-hotspot
$ cmake -DCMAKE_PREFIX_PATH=$HOME/qt-5.15.2 ../hotspot
…snip...
-- The following OPTIONAL packages have been found:

 * KF5Service (required version >= 5.47.0)
 * KF5Completion (required version >= 5.47.0)
 * KF5JobWidgets (required version >= 5.47.0)
 * KF5Sonnet (required version >= 5.47.0)
 * KF5TextWidgets (required version >= 5.47.0)
 * KF5Auth (required version >= 5.47.0)
 * KF5Codecs (required version >= 5.47.0)
 * KF5WidgetsAddons (required version >= 5.47.0)
 * KF5XmlGui (required version >= 5.47.0)

-- The following REQUIRED packages have been found:

 * Qt5Gui (required version >= 5.15.2)
 * Qt5Test
 * Qt5Svg
 * Qt5 (required version >= 5.15)
 * LibElf
 * Elfutils
 * ECM (required version >= 1.0.0)
 * Threads
 * KF5ThreadWeaver
 * KF5ItemModels
 * KF5WindowSystem
 * KF5Notifications
 * KF5IconThemes
 * KF5ItemViews (required version >= 5.47.0)
 * KF5Solid (required version >= 5.47.0)
 * Qt5Network (required version >= 5.8.0)
 * Gettext
 * KF5I18n (required version >= 5.47.0)
 * KF5CoreAddons (required version >= 5.47.0)
 * Qt5Core (required version >= 5.8.0)
 * Qt5Widgets (required version >= 5.8.0)
 * KF5ConfigWidgets (required version >= 5.47.0)
 * KF5Parts
 * KF5

-- The following RUNTIME packages have not been found:

 * LibRustcDemangle, Demangling for Rust symbols, written in Rust., <https://github.com/alexcrichton/rustc-demangle>
   Demangling of Rust symbols

-- The following OPTIONAL packages have not been found:

 * Zstd

-- The following REQUIRED packages have not been found:

 * KDDockWidgets
   KDDockWidgets is a Qt dock widget library written by KDAB, suitable for replacing QDockWidget and implementing
 advanced functionalities missing in Qt. https://github.com/KDAB/KDDockWidgets

CMake Error at /usr/local/share/cmake-3.21/Modules/FeatureSummary.cmake:464 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:81 (feature_summary)


-- Configuring incomplete, errors occurred!
See also "/home/dope/sb/build-hotspot/CMakeFiles/CMakeOutput.log".
See also "/home/dope/sb/build-hotspot/CMakeFiles/CMakeError.log".
```

**Comment by milianw** [comment]
you are misinterpreting the message - your error is the missing dependency of KDDockWidgets:

```
-- The following REQUIRED packages have not been found:

 * KDDockWidgets
   KDDockWidgets is a Qt dock widget library written by KDAB, suitable for replacing QDockWidget and implementing
 advanced functionalities missing in Qt. https://github.com/KDAB/KDDockWidgets
 ```

rustcdemangle is only a runtime depencency (and optional then as I said)
