### ISSUE TITLE
display helpful info if file open limit exceeded

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#290]
On a large application (like LibreOffice), it is fairly easy to exceed the default maximum number of open files (1024), which results in the stack traces being full of "??"

It would be nice if the UI could catch this and display a helpful error message, something like

"We needed to open lots of files to unwind the stack, more than the OS currently allows, suggest you run ulimit -n 64000 before launching"

THankS!

**Comment by milianw** [comment]
I concur, but at the same time I wonder - why are we opening so many files? I don't think LO has 1024 libraries linked that we need to open. Or is that the overall system limit and thus shared with other applications?

Basically there should just be at most one handle per ELF and potentially one more for the split debug file...

**Comment by grandinj** [comment]
AFAIK, the ulimits are per process.

I'll do an lsof in the morning to see what handles are open

**Comment by grandinj** [comment]
The specific error message I get is:

570284 failed to attach state Couldn't find architecture of any ELF
failed to report elf for pid = -1 : ElfInfo{localFile="/lib/modules/5.8.0-53-generic/kernel/drivers/ata/libahci.ko", isFile=true, originalFileName="libahci.ko", originalPath="/lib/modules/5.8.0-53-generic/kernel/drivers/ata/libahci.ko", addr=ffffffffc0127000, len=9000, pgoff=0, baseAddr=n/a} : Too many open files
570284 failed to attach state Couldn't find architecture of any ELF
569249 failed to attach state Couldn't find architecture of any ELF


And I'm attaching an lsof list of open file handles

[lsof.txt](https://github.com/KDAB/hotspot/files/6492795/lsof.txt)

**Comment by grandinj** [comment]
Now that I think about it a bit more, this is a rather heavy duty stress test for Hotspot - I am using perf to sample a run of our unit test suite, which is pretty comprehensive, so feel free to just say 

"sorry buddy, you are on your own when you do stuff like that"

<grin>

**Comment by milianw** [comment]
Yes I think that's what I have to say :)

I don't believe we can share/reuse the opened files for the different processes recorded in the `perf.data` file, as elfutils takes ownership of the handles afaik.

And personally I really have to say that a meager 1024 files as a limit is plain stupid. This also means you cannot use any IDE with a file watcher on a large project like LO already, no?

Really, just bump your file limit and be done with it :)

**Comment by grandinj** [comment]
Oh, I wasn't suggesting that you try to complicate the Hotspot codebase, file-handle wise, just that it notes the error and displays a helpful error message, exactly something like "You need to raise your file handle limit"

:-)

**Comment by milianw** [comment]
http://0pointer.net/blog/file-descriptor-limits.html -> care to submit a patch to add something like https://github.com/systemd/systemd/blob/e7901aba1480db21e06e21cef4f6486ad71b2ec5/src/basic/rlimit-util.c#L373 

I guess this should solve this issue on all systemd distros at least

**Comment by grandinj** [comment]
I'd love to help, but I can't build KDAB hotspot on my distro (Ubuntu 20.10)

**Comment by milianw** [comment]
What's the problem? You can download a separate Qt 5.15 and compile it against that, no?

**Comment by grandinj** [comment]
I sure I could build KDAB __eventually__ but

(a) My enthusiasm wanes with every extra dependency that I have to figure out to how to download, configure, build (with all of it's dependencies and build-time funnies)

(b) I spend most of my time working on LibreOffice, and my in experience, installing other versions of libraries already present on the box tends to result in messing up my LibreOffice build, which I am sorely loathe to do.

In LibreOffice we download stuff to an externals/ folder, and build it and link to it directly, but that kind of functionality doesn't seem to be part of off-the-shelf build systems.

We really need something like CPAN for C++

**Comment by milianw** [comment]
not an issue for myself (and apparently noone else) so I'll close this. still, if anyone wants to work on that - patches welcome!

**Comment by GitMensch** [comment]
I've tripped over this for a system-wide sampling with lots of processes; any idea what may help if opening hotspot as root does not?

Is there anything hotspot could do?
