### ISSUE TITLE
Question how do elfutils and AppImage correlate?

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#293]
https://github.com/KDAB/hotspot#broken-backtraces references elfutils and a commit that should be part of elfutils 0.170.
The current version of elfutlils is 0.183, so if that would be included in the AppImage it may be reasonable to suggest using that one instead (or simply suggest to build current elfutils without any version reference).

**Comment by milianw** [comment]
the readme is trying to say: use 0.170 or newer that contains that commit. if you want to rephrase it for clarity, patches welcome. feel free to say that the appimage should contain a recent appimage that includes this.
