### ISSUE TITLE
optimize filtering

### ISSUE THREAD

**Issue by milianw** [KDAB/hotspot#30]
The current filtering is not as efficient as it could be. Most notably, we concatenate the symbol+binary strings. Instead we should:

- inherit from QSortFilterProxyModel
- in its `filterAcceptsRow` overload, ask the model directly whether it matches the given needle
- in the model, check against the symbol contents

Note that we cannot simply return a `Data::Symbol` variant, as that would still allocate the data on the heap for type erasure.

**Comment by GitMensch** [comment]
Is the "concatenate symbol + binary strings" still true?

**Comment by milianw** [comment]
yes, see e.g. `treemodel.h`:

```

        if (role == FilterRole) {
            // TODO: optimize
            return QString(Util::formatSymbol(item->symbol, false) + item->symbol.binary);
```

**Comment by GitMensch** [comment]
Then #292 seems to be related performance wise (at least for the "filter out (only this) binary").
