### ISSUE TITLE
  Could not find a configuration file for package "Qt5" that is compatible   with requested version "5.15"

### ISSUE THREAD

**Issue by feller23** [KDAB/hotspot#304]
**Describe the bug**
I get the error "  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.15" when i run cmake on Ubuntu 20.04 focal
 Full Error is below 

CMake Error at CMakeLists.txt:37 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.15".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.12.8
    /lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.12.8

-- Configuring incomplete, errors occurred!
See also "/home/mininet/build-hotspot/CMakeFiles/CMakeOutput.log".

![mininetCmakeError](https://user-images.githubusercontent.com/20794371/124110929-2f5a9000-da82-11eb-8651-cfc194859ddc.png)

**Comment by milianw** [comment]
as the error says, your qt is too old. update
