### ISSUE TITLE
When will we have `annotate`?

### ISSUE THREAD

**Issue by fzyzcjy** [KDAB/hotspot#336]
Hi thanks for the lib! I wonder when will have the `perf annoate` GUI? It is very useful!

**Comment by GitMensch** [comment]
The code written by @lievenhey referenced here was included by @milianw as part of #349 - is this considered to be fixed now, too?

If yes README.md may need an adjustment again, still saying:

>  But a proper annotation view like perf annotate on the source level, is currently missing

In any case I'm eager to run the new CI build with those changes!
