### ISSUE TITLE
unhandled asm line format

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#340]
https://github.com/KDAB/hotspot/blob/df39e783a997a7495ba654853720395b3aa0b238/src/models/disassemblyoutput.cpp#L49-54 has an explicit check for that. I'm not sure if this is a bug and something should be done or if this is just an ignorable warning (in which case this info _may_ be added to the message):

```
unhandled asm line format: "/root/.debug/usr/lib64/libc-2.17.so/5861cfac90a2037fb2f649fdaf1b679b2a25f1e7/elf"
unhandled asm line format: "00000000000897c0 <__GI_memset>"
unhandled asm line format: "/root/.debug/usr/lib64/libgmp.so.10.2.0/b8fee69329c044ac323d5e213cc747937d5228db/elf"
unhandled asm line format: "0000000000032060 <__gmpn_sizeinbase+0x70>"
```

**Comment by lievenhey** [comment]
I believe that it is too ample, since we don't want to remove lines like `11d9:  74 0d   je 11e8 <_start@@Base+0xc8>`
