### ISSUE TITLE
unhandled event type 79 73 74 PERF_RECORD_TIME_CONV PERF_RECORD_THREAD_MAP PERF_RECORD_CPU_MAP

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#341]
Low-priority, primarily adding it to allow people finding it in the issue tracker.

```
unhandled event type 79   PERF_RECORD_TIME_CONV
unhandled event type 73   PERF_RECORD_THREAD_MAP
unhandled event type 74   PERF_RECORD_CPU_MAP
```

_Originally posted by @GitMensch in https://github.com/KDAB/hotspot/issues/164#issuecomment-792822540_

@milianw already noted
> The unhandled events you can safely ignore too I believe.

and that's what I'll do here because those events are very seldom, not like the mass-events from #177.

**Comment by milianw** [comment]
current master should not show this anymore
