### ISSUE TITLE
perfparser upstreaming?

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#342]
This goes out especially to @milianw: Can you please contact GitHub support (either [via mail](mailto:support@github.com) or via ["ticket"](https://support.github.com/contact?tags=rr-general-technical)) to ask https://github.com/KDAB/perfparser to be registered as fork of https://github.com/qt-creator/perfparser?

Despite the additional attribution and the option to find both easier from the other it would also make pulling changes from upstream much easier and also allows easier sending patches upstream, even if that isn't planned "yet".

**Comment by milianw** [comment]
I added the link now. and I regularly take care of upstreaming changes to perfparser (like I did the other week). I'm going to close this
