### ISSUE TITLE
[D] demangle D's symbol

### ISSUE THREAD

**Issue by ryuukk** [KDAB/hotspot#357]
Hello,

First of all, thanks for your tool, it helped me profile my program very easily!

**Is your feature request related to a problem? Please describe.**

Currently, the program shows mangled name for D programs, wich can be very hard to read

The solution would be to demangle the names automatically, using the ``ddemangle`` tool available here: https://github.com/dlang/tools

On Arch it is available throught the package: ``dtools``, executable: ``/usr/bin/dtools-ddemangle``

**Comment by ryuukk** [comment]
Apparently it is already available: https://github.com/KDAB/hotspot/tree/master/scripts/d-demangle

I missed it when looking through the repo, so this can be closed

**Comment by John-Colvin** [comment]
it doesn't appear to work in the assembly view
