### ISSUE TITLE
Running AppImage creates duplicate weird entries in kde icononly taskmanager

### ISSUE THREAD

**Issue by xgdgsc** [KDAB/hotspot#358]
**Describe the bug**
When I click and run hotspot-v1.3.0-166-g26a7e77-x86_64.AppImage. My task bar in Kubuntu 20.04 gets corrupted with invalid pinned entries like:

![image](https://user-images.githubusercontent.com/1189869/149292164-f5217e77-b104-47a2-be3e-3d033ec0814c.png)

The entries with "?" are corrupted pinned items. (Nautilu and wechat in this case, the 2 after the second "?")

Before running hotspot it's like this:

![image](https://user-images.githubusercontent.com/1189869/149293459-c1f2f914-14a3-474e-9643-6f9f5fa1ebc4.png)

**To Reproduce**
1. click and run hotspot-v1.3.0-166-g26a7e77-x86_64.AppImage
2. see  kde icononly taskmanager
 

**Expected behavior**
Nothing happens to  kde icononly taskmanager

**Screenshots**
![image](https://user-images.githubusercontent.com/1189869/149292164-f5217e77-b104-47a2-be3e-3d033ec0814c.png)

**Version Info (please complete the following information):**
 
 - hotspot version (appimage? selfcompiled?): hotspot-v1.3.0-166-g26a7e77-x86_64.AppImage.

**Comment by xgdgsc** [comment]
And "Applications" in KRunner would become empty.

**Comment by lievenhey** [comment]
I can confirm this issue.
running the appimage from the command line reveals `"applications.menu"  not found in  ("/etc/xdg/menus")`
after creating a symlink from kf5-applications.menu to applications.menu (`sudo ln -s /etc/xdg/menus/kf5-applications.menu /etc/xdg/menus/applications.menu`) it works correctly

**Comment by lievenhey** [comment]
further investigation shows that kubuntu doesn't follow https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html
after manually settings `XDG_MENU_PREFIX` to `kf5-` everything works as intended
