### ISSUE TITLE
Can't fine perfparser export as described in readme

### ISSUE THREAD

**Issue by Ten0** [KDAB/hotspot#362]
**Describe the bug**

Readme describes the following process to obtain a fully self-contained export:

https://github.com/KDAB/hotspot/blob/72abf3065ecd1ae5f5ba5fe78fb0d48984df9f95/README.md#L323-L326

I've just downloaded the latest version from the AUR and it doesn't exist:
![image](https://user-images.githubusercontent.com/9094255/151874407-f8ca61ab-ca05-49b7-af39-7a9c1fcab3fb.png)

**Version Info (please complete the following information):**
 - hotspot version :72abf3065ecd1ae5f5ba5fe78fb0d48984df9f95

**Comment by lievenhey** [comment]
the hotspot package on the AUR is based on hotspot 1.3.0 which does not include this feature. hotspot-git includes this feature.

**Comment by MTSranger** [comment]
Is there a plan to release a new version with this feature so we don't have to build from source? The last release was in 2020.

**Comment by GitMensch** [comment]
@MTSranger the last release was done with 1.4.0 today :-)
