### ISSUE TITLE
Can we have a 1.4.0 milestone / release planning?

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#365]
It would be really nice to have a milestone for the next release, to start tracking the issues already done for the later release note and to get an idea where the release "stands". There were already nearly 200 commits since the last release https://github.com/KDAB/hotspot/compare/1.3...master and as the README suggests "Most users should probably [install hotspot](https://github.com/KDAB/hotspot#getting-hotspot) from the distro package manager" - where commonly only releases are found.
I'd guess the current master is "good as is", and if/when the open PRs are included (they _look_ quite mature) the amount of changes looks already huge for a release and the additional features, too.

Note: https://github.com/KDAB/hotspot/milestones show some issues that seem to be already either solved (partially with commits "not belonging to this repo") or are still open - these may be moved to a backlog milestone or to 1.4.0, too.

**Comment by milianw** [comment]
I updated the appimage currently and do plan to do a 1.4 release "soon"

as this is purely free time driven, I'm not going to spent time on milestoneing or release planning, sorry

**Comment by GitMensch** [comment]
The updated appimage and the note about "soon" release is totally enough.
Thanks!

**Comment by milianw** [comment]
https://github.com/KDAB/hotspot/releases/tag/v1.4.0
