### ISSUE TITLE
Invalid memory read requested by dwfl

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#373]
**Describe the bug**
Using appimage CI build 1.3.0-166 opening some perf.data raises a bunch of
> Invalid memory read requested by dwfl fffffffffffffff8

**To Reproduce**
1. Download CI build 1.3.0-166
2. app-extract (no fuse)
3. open it with some perf.data
4. See error - **139 exact identical lines of this error message in the console**

**Version Info:**
 - Linux Kernel version: 3.10.0-514.16.1.el7.x86_64
 - perf version: 3.10.0-1127.19.1.el7.x86_64.debug
 - hotspot version: 1.3.0-166 appimage

**Comment by milianw** [comment]
This isn't necessarily a bug - this can happen e.g. when you have large stacks and unwinding exceeds the 4K page snippets that are put into your perf.data file during record.

So for now, I suggest you ignore this warning or suggest what else to do about this.

**Comment by GitMensch** [comment]
The biggest part of traces where I've seen this is main -> 9 stack elements -> libpq (postgresql client). I doubt that this would qualify for a large stack. Is it possible to have more output in this case?
Do you know where the warning is produced?
Could it be possibly mapped to a warning like "too big stack [then place the available stack]"?

**Comment by milianw** [comment]
The message is emitted by perfparser as a reaction to an error reported by dwfl.

The problem with handling it properly is that there are multiple scenarios where this can happen. The above is just one potential cause. Another would happen when the binary doesn't provide good unwind tables. Or when there's a mismatch between the stack copy and the recorded stack pointer, see e.g. issue #194.

All of this is a lot of work to get right, and for me... it's much simpler to ignore this and only look at the warnings when I want to debug a broken result.

If you have concrete suggestions on how to improve the situation, by all means please provide a patch.

**Comment by milianw** [comment]
closing, please provide a patch when you want to see things improved in this area
