### ISSUE TITLE
Find way to access /proc/kallsyms

### ISSUE THREAD

**Issue by lievenhey** [KDAB/hotspot#376]
**Is your feature request related to a problem? Please describe.**
Kernel symbols are not shown by default since my user does not have permissions to open /proc/kallsyms 

**Describe the solution you'd like**
Find way to do this

**Describe alternatives you've considered**
running hotspot as root

**Comment by milianw** [comment]
the script to elevate your privileges handles this, most notably this part afair:

```
 echo "0" | sudo tee /proc/sys/kernel/kptr_restrict
```

**Comment by lievenhey** [comment]
I also should add a remount to `/sys/kernel/tracing/` to to make it possible to use tracepoints
