### ISSUE TITLE
show version number in Help->About Hotspot

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#391]
**Is your feature request related to a problem? Please describe.**
Especially when on a machine with Hotspot installed I sometimes wonder: which version is that.
This information is also useful when reporting issues or looking for existing reports.

**Describe the solution you'd like**
show version number in Help->About Hotspot

**Describe alternatives you've considered**
Check with `hotspot --version`.

**Additional context**
It would be good to show also a "source date" next to the version number.

**Comment by milianw** [comment]
including the "source date" or git sha is cumbersome, I don't want to do that really.
