### ISSUE TITLE
"Continuous build" on Github Releases seems to be outdated.

### ISSUE THREAD

**Issue by vi** [KDAB/hotspot#397]
I see many commits from 2022, but "continunous" built is from 2020.

Is there a recent pre-built AppImage of Hotspot? Maybe there are enough changes to make a proper new release/

**Comment by GitMensch** [comment]
As _ posted by @milianw in https://github.com/KDAB/hotspot/issues/390#issuecomment-1235347601_ early September:

> > The CI builds don't provide an AppImage, do they?

> Not yet, no - I'll build one manually next week (and do a proper new release too 🤞)


So I guess a new release is "in sight".

**Comment by Ristovski** [comment]
@milianw Any news on this? There is still no new release

**Comment by milianw** [comment]
sorry for the delays again. @lievenhey and me are working on proper automatic appimage generation and we are close to get that done. maybe even later today already. I'll keep you posted

**Comment by GitMensch** [comment]
Thanks for the update, so it seems that the README should be adjusted (links to releases, may get an own note concerning where to download the nightly (?) AppImage [I'd guess: head to https://github.com/KDAB/hotspot/actions, clock on the first green one , then download the artifact]).

In theory a last step could be added which replaces the AppImage in the continuous build "release", too, including a note on its date / revision in the text.

@milianw: Do you still want to get out "a proper release" soon? If yes: Is there a milestone /  tasklist for that?

**Comment by milianw** [comment]
@GitMensch I've updated the README and [continuous release](https://github.com/KDAB/hotspot/releases/tag/continuous) with documentation on how to obtain the AppImage.

And yes, a proper release is still planned. Basically from the git master version.

**Comment by GitMensch** [comment]
Do you have any hints how to download a single - or even better - the most current artifact via command line?
I fail to get that working :-/ [download via browser works]
