### ISSUE TITLE
incorrect aggregation base in bottom down view when excluding threads

### ISSUE THREAD

**Issue by jeff-dagenais** [KDAB/hotspot#403]
**Describe the bug**
Before the recent 596f5e3759, the aggregate by thread didn't work at all in my testing. Now it does create separate columns, using the thread name, awesome! However, as soon as you exclude one thread in the bottom event view, it seems like the top function (likely where the execution was at the moment of perf record sampling) actually shows up in the bottom as the base!

So basically when selecting 
Suppose I have a `main()` which calls `myFunc1()`, which calls `myFunc2()`, which calls `myFunc3()`, I get stacks that look like this:

- myFunc2()
- myFunc1()
- main()
- __libc_start_call_main
- __SI__libc_start_main_alias_1_0
- _start
- myFunc3()

**To Reproduce**

1. Perf record a multi-threaded program
2. select "Aggregate cost by: threads"
3. right click on a thread in the bottom event view, then "Exclude Thread #12345"4. 
4. Inspect the call stack

**Expected behavior**
The thread name should should still appear at the bottom, and the right function (e.g. `myFunc3()`) should still be at the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/383714/194142315-1a6ddc0a-3e73-40dd-ab78-3e543f657995.png)
![image](https://user-images.githubusercontent.com/383714/194143346-1d3791a3-ac7e-4b49-b360-e806a80da941.png)

**Version Info (please complete the following information):**

- Linux Kernel version: in docker desktop on macOS, Linux eb1328965548 5.10.124-linuxkit 
- perf version: linux-tools-generic: Installed: 5.19.0.15.15
- hotspot version: self compiled 07825e6
- elfutils version: self compiled, 6cb01b4ef3cdd4f83d21bbcec72fa66712ac14e6

**Comment by milianw** [comment]
@jeff-dagenais do you have time to investigate this issue?

**Comment by jeff-dagenais** [comment]
Sorry for late reply. Been swamped. Glad to see the community effect in action. Thanks @lievenhey !
