### ISSUE TITLE
Additions to `.gitignore`

### ISSUE THREAD

**Issue by elsandosgrande** [KDAB/hotspot#411]
### Discussed in https://github.com/KDAB/hotspot/discussions/405

<div type='discussions-op-text'>

<sup>Originally posted by **elsandosgrande** October  8, 2022</sup>
It would be nice to add some common files to `.gitignore`, like VS Code settings and workspace settings files, or clangd compilation database files. Specifically:
```gitignore
.vscode # directory used by VS Code for preferences and the like
compile_flags.txt # list of used compilation flags, handwritten
compile_commands.json # compilation database, generated by CMake; https://clangd.llvm.org/design/compile-commands#where-do-compile-commands-come-from
*.code-workspace # VS Code workspace file
.cache # clangd's index cache; https://clangd.llvm.org/design/indexing.html
```

Thank you in advance!!
</div>

---

I'm not sure if discussions are simply not checked periodically or what, but I thought to create an issue ticket from mine since it's seemingly been untouched for around a month.

**Comment by milianw** [comment]
patches welcome, please expand it as needed for your editor/development workflow. I'm not using VS Code so don't expect me to filter out the files it needs

**Comment by milianw** [comment]
I'll close this. feel free to send in patches to expand the gitignore as needed
