### ISSUE TITLE
FR: add option to set source paths

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#418]
Double clicking on a location in the callee/caller pane that has relative source file references I get the "failed to find file for location".

* recording: one locally before opening hotspot with `perf record --sample-cpu -z --aio --call-graph dwarf`
* original sources under: /home/me/project/lib
* original build under /home/me/project/build/lib - using relative files starting with ../../lib 
* use of installed binaries under /opt/install/project/lib
* everything works without any setup in GDB
* hotspot fails to resolve the source

I _think_ this likely can be worked around using the configuration, but as my tinkering with that did not work out asking for help.

**Comment by milianw** [comment]
See the other report: please help us reproduce this issue by providing a project we can compile that triggers this behavior

**Comment by GitMensch** [comment]
The other issue is about handling stored debug info correct.
This issue is about the option to configure paths. How would I configure Hotspot in the following scenario:

~~~
pushd tests/test-clients
gcc $(PWD)/cpp-stdin/main.cpp
popd
mv tests/test-clients/cpp-stdin ./cpp-stdin 
perf record --sample-cpu -z --aio --call-graph dwarf ./tests/test-clients/a.out
~~~

* source file not on the original place
* hotspot can't find that file
* user wants to configure lookup paths

**Comment by milianw** [comment]
Ah I see, yes we should probably add some kind of path mapping or at least a list of source paths to query.

**Comment by GitMensch** [comment]
Note: GDB comes with both `directories` and `substitute-path` settings; but I _guess_ the first one would work for most cases where perf is used.

**Comment by GitMensch** [comment]
kind of related to #450 - which is about binary data as both are easily stored for inspecting perf data later / on a different machine
