### ISSUE TITLE
Disassembly window: allow to "scroll by click"

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#423]
**Is your feature request related to a problem? Please describe.**
Some source lines can have a lot of assembly lines and some functions can be quite long, too.
Co-inspecting the Assembly to the Source Code is hard in this case - only visually.
There already is a "visual match" via hovering (which "highlights" the code on the other side) but it takes quite long to navigate in the cases mentioned above.

**Describe the solution you'd like**
When clicking on a line in the source code view, then jump to the start of the disassembly for this line and vice versa (= similar to the highlighting on over but scroll/position there instead)

**Describe alternatives you've considered**
Scroll around with re-positioning the views until finding the match via highlight.

**Comment by milianw** [comment]
ah, I just had the same idea and implemented it in df72b93eeace3ef2000e1288dac24479257747af without realizing you had a feature request for this too :)

**Comment by GitMensch** [comment]
"works" in general, the relevant line _is_ scrolled; ideally this could be adjusted to scroll the relevant line to top or to the middle of the screen.
So not very important, but something to possibly inspect.

"Workaround": scroll to last line in Disassembly first, then double-click on the line in the source view (or vice versa) and you'll see the relevant line on top instead of the last line.
This _could_ be done via code, too - before selecting the line just position to the last line before.

This would also provide the same result (relevant line at top) instead of making it depending on where the view currently is positioned.
What do you think?

**Comment by GitMensch** [comment]
Also: please consider to change that from double-click to click as there is already a very different (and super cool, and undocumented) feature on double-click in the assembly view: when doing that on a callq instruction line the disassembly view jumps to the function, if available.  (side question: how can one get back?)

**Comment by GitMensch** [comment]
ping @milianw on the "click vs. double-click"

**Comment by milianw** [comment]
@GitMensch make this a separate issue
