### ISSUE TITLE
command line option or - preferable - a separate tool to convert perf.data to .perfparser

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#440]
**Is your feature request related to a problem? Please describe.**
Recorded perf data is not unlikely to be "out of date" when the application/os changes.
I was therefore happy to see the following entry in the 1.4 release notes:
> you can export and import data from hotspot in a custom format that is efficient to load and self-contained, meaning exported data can be read on any other machine with hotspot and does not require access to the original client application code for unwinding anymore

When opening Hotspot and opening a trace, I do see  "Save As" ... `*.perfparser`, which I _assume_ to be this new format.
Using "File Open" does not contain a dropdown entry for `*.perfparser`, but I guess this would be the correct way to open it.

As I'd like to "directly convert" after recording a command line option for that would be very useful.

**Describe the solution you'd like**
I'd _like_ a solution that works even without any X initialization, enabling conversion even in headless / CI systems. I _guess_ that would mean that the main hotspot binary cannot be used for that, but I don't know.

**Describe alternatives you've considered**
Open by hand, save by hand; but that cannot be done automated.

**Additional context**
I'd guess that for the Disassembly view the "original client application" binaries and code must be still available, no? Are there other places where this would be necessary? Could I copy those over to a second machine and just reference them in the second instance?

**Comment by GitMensch** [comment]
It is in code-wise, can you please add some docs on this, too?

**Comment by milianw** [comment]
What is needed outside the `--help` output?

**Comment by GitMensch** [comment]
Find a good place in the README to put the output of `--help` to would be fine.

**Comment by milianw** [comment]
> Find a good place in the README to put the output of `--help` to would be fine.

patches welcome

**Comment by GitMensch** [comment]
OK, patches will come :-)

What do you think of splitting out README.md into HACKING.md (the build instructions "from source" and "debugging Appimage", linked from the main README)?

**Comment by milianw** [comment]
yes sounds like a good idea to me
