### ISSUE TITLE
Apply Filtering "Time Line" to "Flame Graph"

### ISSUE THREAD

**Issue by theHamsta** [KDAB/hotspot#451]
**Is your feature request related to a problem? Please describe.**
The "Time Line" gives me the perfect overview where the interesting parts of my application happen temporarily. It let's me filter from start to end time and also per thread. However, I can now apply the same filtering to the flame graph to only consider samples in given time interval. 

**Describe the solution you'd like**
It would be very nice if I could apply the filtering I do in the "Time Line" also to other views like the "Flame Graph", so that only samples from given start to end time or thread are considered. This could be done either automatically or via a checkbox in the flamegraph/call graph

**Describe alternatives you've considered**
I could use other software that supports this feature or restrict my benchmarks to instrument only the interesting time range.

**Additional context**
N/A

**Comment by milianw** [comment]
What you are describing is the behavior of the tool. I think there is some kind of misunderstanding? When you select a time range and "filter in by time" then all the views, i.e. both the tables as well as the flame graph get updated accordingly. If not, then that's a bug - please show what you are doing in a screencast if that doesn't work for you

**Comment by milianw** [comment]
I wonder if we should ditch zooming completely, as it's probably not really that useful in practice... Afair I copied that UX from some other tool, but I never really use it myself either :shrug:

What do you think?

**Comment by theHamsta** [comment]
> I wonder if we should ditch zooming completely, as it's probably not really that useful in practice... Afair I copied that UX from some other tool, but I never really use it myself either 🤷
> 
> What do you think?

I'm not sure about that whether someone uses this feature. I don't use it long enough to tell whether I would use it. Maybe there could also be an overlay over the flamegraph that warns the user that time line and flamecharts are out of sync and offers the user to apply the zoom also to the flamegraph
