### ISSUE TITLE
cmake fails to find ElfUtils

### ISSUE THREAD

**Issue by yurivict** [KDAB/hotspot#460]
```
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ElfUtils (missing: LIBDW_LIBRARIES LIBDW_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindElfUtils.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:48 (find_package)
```

Something is wrong with cmake/FindElfUtils.cmake

But why do you need to have cmake/FindElfUtils.cmake when pkg-config can find FindElfUtils? Instead of providinf cmake/FindElfUtils.cmake you should use pkgconfig.

**Comment by yurivict** [comment]
I found the problem - libutils was missing during build for other reasons.

**Comment by milianw** [comment]
so not our bug, right? if you think otherwise please provide better information on how to reproduce
