### ISSUE TITLE
unknown error related to executable/libraries

### ISSUE THREAD

**Issue by Overcraft90** [KDAB/hotspot#461]
**Describe the bug**
After launching the app (either the `AppImage` or the `release version` of Hotspot, the GUI reports some missing packages and a missing location for the executable.

**To Reproduce**

1. Go to 'Show Applications' or either 'Double-click' the `AppImage`
2. Click on 'Hotspot'
3. Check the 'Parser Errors' box

**Expected behavior**
I should be able to visualize a Flamegraph (tab) out f my `perf.data` file.

**Screenshots**
_**From the `release version` app**_
![Screenshot from 2023-01-23 11-22-55](https://user-images.githubusercontent.com/98895614/214131416-b893adff-37e5-413e-8440-c78957449af0.png)

_**From the `AppImage`**_
![Screenshot from 2023-01-23 11-25-48](https://user-images.githubusercontent.com/98895614/214131665-b926672c-287e-4606-96c9-a4988521becf.png)

**Version Info (please complete the following information):**

- Linux Kernel version: `Ubuntu 22.04.1 LTS` on `5.15.0-58-generic`
- perf version: `5.15.74`
- hotspot version (appimage? selfcompiled?): `hotspot 1.3.0` and `appimage:1.4.1`
- if self-compiled hotspot, what version of elfutils:

**Additional context**
I have both `vg` and, apparently also all other libraries (unless I'm not missing something those are present by default in Ubuntu). Still, I cannot figure out why my `peft.data` cannot be visualized correctly and I'm prompted with those errors.

**Comment by Overcraft90** [comment]
No I didn't..., I just read the related section but I'm not quite sure how to do it.

In the meantime. I though there was an issue with my machine, so I started to build from source. I got to the point where the build is killed because I'm missing the `KDDockWidgets`. I tried to install it in a specific location (_e.g._ /usr/local/bin), but it seems `hotspot` is not able to "see it".

Is there any preferred location where to installe the `KDDockWidgets`, maybe the default one would work? Or either should I move an executable generated after the build to my system BIN folder? Let me know, this might help in getting around the problem. Thanks!

**Comment by GitMensch** [comment]
> Is there any preferred location where to installe the `KDDockWidgets`, maybe the default one would work? Or either should I move an executable generated after the build to my system BIN folder?

This seems unrelated to this issue, but you may want to have a look at [this example recipe](https://github.com/KDAB/hotspot/blob/421e75f6e9ae22da39f82daf7b40410e27433ad7/.gitpod.yml): the "trick" is to install both at the same place by telling that cmake up-front - in the example `-DCMAKE_INSTALL_PREFIX=/opt/KDAB` (for both KDDockWidgets + Hotspot).

Concerning this issue, which may be a non-issue after all:

> show us the flame graph, is it really broken? the data might be useable despite some debug symbols being missing

**Comment by Overcraft90** [comment]
> This seems unrelated to this issue, but you may want to have a look at this example recipe: the "trick" is to install both at the same place by telling that cmake up-front - in the example -DCMAKE_INSTALL_PREFIX=/opt/KDAB (for both KDDockWidgets + Hotspot).

Thanks for the hint I've now been able to build from source. I realized, however, that this thing with the `debuginfod` is important as also during the `cmake` process the operation terminated successfully returning the following:

> -- Looking for dwfl_get_debuginfod_client - not found

Now, back to the **_Flame Graph_** issue I got the `AppImage` — for some reason the executable built from source was unresponsive _e.g._ Open File was not working with the following shell error message: `kf.coreaddons: "Could not find plugin konsolepart"` — went to settings and added this URL [https://debuginfod.ubuntu.com/](https://debuginfod.ubuntu.com/) based on my machine distro and architecture. Everything works smoothly, no errors are prompted, but I still get the same parser issues as before. Below the _**Flame Graph**_
![Screenshot from 2023-01-26 17-44-01](https://user-images.githubusercontent.com/98895614/214993953-1bb07e1d-8a28-4d10-8b86-3bb560d1b2aa.png)

What would be nice to know/fix is why the executable I built from source is not working correctly? Do you want me to open a new issue. Thanks for your help!

**Comment by milianw** [comment]
the app image is fine, so this is a non-issue?

I don't have time to give cmake build support. and the konsole part is optional, so that's not the issue you are seeing. debug it yourself, figure out why it's "unresponsive" and then create a new issue that explains the issue with steps for us to reproduce
