### ISSUE TITLE
AppImage: Crash entering Caller / Callee tab

### ISSUE THREAD

**Issue by rainman110** [KDAB/hotspot#462]
**Describe the bug**
I downloaded the current AppImage of hotspot (1.4.1).

When I try to view the caller / callee tab, hotspot crashes instantaneously. 

Note: this does not happen with an  older hotspot version (1.3.0-166 AppImage)
Note: this seems to be related due to a missing xdot renderer. I tried to install `xdot` via `apt`, but it did not solve the problem.

**To Reproduce**

1. Open Perf Data
2. Goto tab Caller / Caller
3. Hotspot crashes to terminal with the error
 ```
Error: Layout type: "dot" not recognized. Use one of:
Error: renderer for xdot is unavailable
/tmp/.mount_hotspoHsl0sE/AppRun.wrapped: Zeile 6: 56864 Speicherzugriffsfehler  LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$bin/hotspot" "$@"
```

**Expected behavior**
No crash ;)

**Screenshots**
 - 

**Version Info (please complete the following information):**

- Linux Kernel version: 4.19.0-22-amd64 /Debian Buster OS
- perf version: 4.19.269
- hotspot version (appimage? selfcompiled?): hotspot-v1.4.1-x86_64.AppImage
- if self-compiled hotspot, what version of elfutils: -

**Additional context**

**Comment by lievenhey** [comment]
Hi,
this is crash is caused by kgraphviewer. @milianw wanted to dig into this.
For now, you can download the appimage from https://github.com/KDAB/hotspot/actions/runs/3894201013 (latest ci run) which does not include kgraphviewer.

**Comment by paulfloyd** [comment]
The artifacts in the link have expired. Would it be possible to get a more permanent fix?

**Comment by lievenhey** [comment]
https://github.com/KDAB/hotspot/suites/12314001604/artifacts/652894756
