### ISSUE TITLE
Wrong assumption about the kauth installation dirs

### ISSUE THREAD

**Issue by krop** [KDAB/hotspot#469]
The helper code assumes the kauth installation dirs can't be customized:

https://github.com/KDAB/hotspot/blob/master/src/authhelper.cpp#L34:
```
        // make install installs the helper to /usr/lib/kauth/ and the elevate script to /usr/lib/libexec
        const QString script = qApp->applicationDirPath() + QLatin1String("/../libexec/elevate_perf_privileges.sh");
```

openSUSE follows the [FHS 3.0 specs](https://refspecs.linuxfoundation.org/fhs.shtml), this causes an error if the elevated privileges box is checked. the kauth helpers are in /usr/libexec/kauth and elevate_perf_privileges.sh is installed into /usr/libexec.

Suggested change: add CMAKE_INSTALL_FULL_LIBEXECDIR or KAUTH_HELPER_INSTALL_ABSOLUTE_DIR (set by KF5AuthConfig.cmake) to hotspot-config.h and use this path.

**Comment by uis246** [comment]
Similar for gentoo, it installs `/usr/lib64/libexec/elevate_perf_privileges.sh` and `/usr/lib64/libexec/kauth/hotspot-auth-helper`. Is this why hotspot prints error "recording failed: Failed to elevate privileges."?
