### ISSUE TITLE
Hotspot application icon not readable in KDE Plasma task list (poor contrast to background)

### ISSUE THREAD

**Issue by krf** [KDAB/hotspot#472]
See screenshot:
  ![image](https://user-images.githubusercontent.com/30826/227024900-a17c8356-1eee-4243-9a49-376dbdb9c9c1.png)

Hotspot's application icon has a poor contrast when shown on the KDE Plasma task list with the Breeze Dark style.

Maybe https://github.com/KDAB/hotspot/blob/master/src/images/icons/128-hotspot_app_icon.png should be used in all occasions? More colorful, easy to read on both light and dark schemes.

**Comment by GitMensch** [comment]
Not sure if the linked one is the best option here - or just the "content" (fire) as it is now (but colorful).
"Icon not readable" also happens with Ubuntu task list.

**Comment by milianw** [comment]
@NunoPinheiroKDAB hey Nuno, could you help me out with this please? I would also  prefer the colorful icon here. I could just take the colorful SVG one and convert it to the requested sizes to override the greyscale images, or is there more required to do that?

**Comment by lievenhey** [comment]
The problem is the breeze twilight theme. In this theme the task bar uses the dark theme and the rest uses the light theme.
