### ISSUE TITLE
hotspot AppImage crash

### ISSUE THREAD

**Issue by majestichou** [KDAB/hotspot#492]
**Describe the bug**
hotspot AppImage crash: /tmp/.mount_hotsporpvdtA/AppRun.wrapped: line 6: 17701 Segmentation fault      (core dumped) LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$bin/hotspot" 
**To Reproduce**

1. downaload hotspot-v1.4.1-x86_64.AppImage
2. chmod u+x hotspot-v1.4.1-x86_64.AppImage && ./hotspot-v1.4.1-x86_64.AppImage
3. open a perf.data
4. Switch to Flame Graph tab
5. Crash! The error information is: /tmp/.mount_hotsporpvdtA/AppRun.wrapped: line 6: 17701 Segmentation fault      (core dumped) LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$bin/hotspot" 

**Expected behavior**
every thing is OK

**Version Info (please complete the following information):**

- Linux Kernel version: Centos7.9
- perf version: 3.10.0-1160.el7.x86_64.debug
- hotspot version (appimage? selfcompiled?):1.4.1
- if self-compiled hotspot, what version of elfutils:

**Additional context**

**Comment by majestichou** [comment]
I try the hotspot-v1.4.0-x86_64.AppImage and it works. But hotspot-v1.4.1-x86_64.AppImage still crash!

**Comment by lostinsea** [comment]
I have the same issue with this AppImage (v1.4.1-x86_64). Running in WSL2.

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64
Ubuntu 22.10

This happens only when I access the caller/callee tab:
Error:
/tmp/.mount_hotspofW5g81/AppRun.wrapped: line 6: 24369 Segmentation fault      LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$bin/hotspot" "$@"

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟

**Comment by GitMensch** [comment]
Can you reproduce that with a [current CI created AppImage](https://github.com/KDAB/hotspot/suites/14550220740/artifacts/823530823)?

**Comment by lostinsea** [comment]
Thanks @GitMensch. I tried it with this image I could not repro it. I was able to use the caller/Callee and Flamegraohs with a super simple data set. Will do a thorough check later today/tomorrow.

However, this is unrelated to the original bug, I noticed that the app crashed multiple times with 

`/tmp/.mount_hotspooerKQs/AppRun.wrapped: line 6: 16738 Segmentation fault      LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$bin/hotspot" "$@"`

**Comment by majestichou** [comment]
> Can you reproduce that with a [current CI created AppImage](https://github.com/KDAB/hotspot/suites/14550220740/artifacts/823530823)?
[current CI created AppImage](https://github.com/KDAB/hotspot/suites/14550220740/artifacts/823530823)? is OK. It does not crash

**Comment by milianw** [comment]
then I'll close this ticket

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟
