### ISSUE TITLE
hotspot crashed during disassembly

### ISSUE THREAD

**Issue by Germano0** [KDAB/hotspot#502]
-- Information about the crash:
hotspot crashed while using disassembler. I am still not sure if I am able to reproduce the crash

Application: hotspot (1.4.1)
Perf 6.4.4

Qt Version: 5.15.10
Frameworks Version: 5.108.0
Operating System: Linux 6.4.10-200.fc38.x86_64 x86_64
Windowing System: X11
Distribution: Fedora Linux 38 (KDE Plasma)
DrKonqi: 5.27.6 [KCrashBackend]

-- Backtrace:
Application: hotspot (hotspot), signal: Aborted
Content of s_kcrashErrorMessage: std::unique_ptr<char []> = {get() = <optimized out>}
[KCrash Handler]
#6  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#7  0x00007f66b24b08b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#8  0x00007f66b245fabe in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#9  0x00007f66b244887f in __GI_abort () at abort.c:79
#10 0x00007f66b26df1e0 in std::__glibcxx_assert_fail (file=file@entry=0x55a5c8f0119f "/usr/include/c++/13/valarray", line=line@entry=588, function=function@entry=0x55a5c8f0aff0 "const _Tp& std::valarray<_Tp>::operator[](std::size_t) const [with _Tp = long long int; std::size_t = long unsigned int]", condition=condition@entry=0x55a5c8f0118c "__i < this->size()") at ../../../../../libstdc++-v3/src/c++11/debug.cc:61
#11 0x000055a5c8ecffe7 in std::valarray<long long>::operator[](unsigned long) const [clone .part.0] [clone .lto_priv.0] (__i=<optimized out>, this=<optimized out>) at /usr/include/c++/13/valarray:588
#12 0x000055a5c8ee46e9 in std::valarray<long long>::operator[] (__i=<optimized out>, this=<optimized out>) at /usr/src/debug/hotspot-1.4.1-1.fc38.x86_64/src/models/disassemblymodel.cpp:123
#13 DisassemblyModel::data (this=0x55a5cafc0460, index=..., role=3) at /usr/src/debug/hotspot-1.4.1-1.fc38.x86_64/src/models/disassemblymodel.cpp:138
#14 0x00007f66b3c5af44 in QModelIndex::data (arole=3, this=<optimized out>) at ../../include/QtCore/../../src/corelib/itemmodels/qabstractitemmodel.h:460
#15 QAbstractItemDelegate::helpEvent (index=..., option=..., view=0x55a5cb4e5080, event=0x7ffdd963b110, this=<optimized out>) at itemviews/qabstractitemdelegate.cpp:401
#16 QAbstractItemDelegate::helpEvent (this=<optimized out>, event=0x7ffdd963b110, view=0x55a5cb4e5080, option=..., index=...) at itemviews/qabstractitemdelegate.cpp:385
#17 0x00007f66b3c44de3 in QAbstractItemView::viewportEvent (this=0x55a5cb4e5080, event=0x7ffdd963b110) at itemviews/qabstractitemview.cpp:1737
#18 0x00007f66b2cb3f56 in QCoreApplicationPrivate::sendThroughObjectEventFilters (receiver=receiver@entry=0x55a5cb4e5b30, event=event@entry=0x7ffdd963b110) at kernel/qcoreapplication.cpp:1190
#19 0x00007f66b39aeb65 in QApplicationPrivate::notify_helper (this=this@entry=0x55a5caa605a0, receiver=receiver@entry=0x55a5cb4e5b30, e=e@entry=0x7ffdd963b110) at kernel/qapplication.cpp:3634
#20 0x00007f66b39b7c75 in QApplication::notify (this=<optimized out>, receiver=0x55a5cb4e5b30, e=0x7ffdd963b110) at kernel/qapplication.cpp:3306
#21 0x00007f66b2cb41a8 in QCoreApplication::notifyInternal2 (receiver=0x55a5cb4e5b30, event=0x7ffdd963b110) at kernel/qcoreapplication.cpp:1064
#22 0x00007f66b2cb43c2 in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
#23 0x00007f66b39b48f1 in QApplication::event (this=0x7ffdd963b680, e=0x7ffdd963b240) at kernel/qapplication.cpp:1901
#24 0x00007f66b39aeb75 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x7ffdd963b680, e=0x7ffdd963b240) at kernel/qapplication.cpp:3640
#25 0x00007f66b2cb41a8 in QCoreApplication::notifyInternal2 (receiver=0x7ffdd963b680, event=0x7ffdd963b240) at kernel/qcoreapplication.cpp:1064
#26 0x00007f66b2cb43c2 in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
#27 0x00007f66b2d05a9b in QTimerInfoList::activateTimers (this=0x55a5cab3aff0) at kernel/qtimerinfo_unix.cpp:643
#28 0x00007f66b2d06399 in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:183
#29 0x00007f66b171348c in g_main_dispatch (context=0x7f669c000ee0) at ../glib/gmain.c:3460
#30 g_main_context_dispatch (context=0x7f669c000ee0) at ../glib/gmain.c:4200
#31 0x00007f66b1771648 in g_main_context_iterate.isra.0 (context=0x7f669c000ee0, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4276
#32 0x00007f66b1710b13 in g_main_context_iteration (context=0x7f669c000ee0, may_block=1) at ../glib/gmain.c:4343
#33 0x00007f66b2d06749 in QEventDispatcherGlib::processEvents (this=0x55a5cab3d570, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#34 0x00007f66b2cb2b6b in QEventLoop::exec (this=this@entry=0x7ffdd963b500, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#35 0x00007f66b2cbadfb in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#36 0x00007f66b3160e9d in QGuiApplication::exec () at kernel/qguiapplication.cpp:1863
#37 0x00007f66b39aeae9 in QApplication::exec () at kernel/qapplication.cpp:2832
#38 0x000055a5c8e58f3c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/hotspot-1.4.1-1.fc38.x86_64/src/main.cpp:233
[Inferior 1 (process 30019) detached]

**Comment by GitMensch** [comment]
So, where you able to reproduce it?
If yes, can you please recheck with the current [AppImage](https://github.com/KDAB/hotspot#for-any-linux-distro-appimage)?

**Comment by Germano0** [comment]
hotspot 1.4.80 from appimage does not crash on the specific disassembly line that I use to make crash Fedora's hotspot 1.4.1
