### ISSUE TITLE
add command line option for debuginfodurls

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#506]
**Is your feature request related to a problem? Please describe.**
We do have the option in the GUI, but do need the setting already when opening a perf file.

**Describe the solution you'd like**
new command line option to add debuginfod urls

**Describe alternatives you've considered**
opening hotspot (often with that file), then edit the settings to include debuginfod urls, then reload

**Comment by lievenhey** [comment]
you can use the environment variable `DEBUGINFOD_URLS`. We don't clear that one. Just append everything you add on the settings page.

**Comment by GitMensch** [comment]
How do we add that to `parser.helpText()`?

**Comment by lievenhey** [comment]
dunno, I will ask @milianw. But since `gdb` also doesn't mention it I would say no.

**Comment by GitMensch** [comment]
GDB has no GUI setting for debuginfod URLs ;-)

**Comment by milianw** [comment]
if you need the option @GitMensch then patches welcome. but the env var as lieven says will be enough in basically all cases and is going to be useful not just for hotspot but all apps (including gdb, heaptrack, ...)

patches adding documentation are welcome as always.

**Comment by milianw** [comment]
Sorry, but I don't understand your question? Do you want to add some text to the help output? Maybe just add something to the end of the `setApplicationDescription()` call?
