### ISSUE TITLE
Symbols not resolved for clang

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#51]
clang version 5.0.0 (trunk 298362)
Qt 5.7.1, built with default mkspec
lab-mandelbrot built with linux-clang-libc++ mkspec

Flamegraph doesn't show inline functions and caller/callee view is missing file/line information

"file lab_mandelbrot" shows that the clang build has no build ID, while a GCC build does have the build ID.

**Comment by milianw** [comment]
It's an elfutils bug, and have reported it upstream now. See also https://github.com/bombela/backward-cpp/blob/master/backward.hpp#L1216 for a potential work-around. That improves the situation, but if it's the right approach I think it should be done within elfutils directly.

binutils doesn't have this problem btw (i.e. addr2line works, eu-addr2line fails).
