### ISSUE TITLE
Cannot run off-CPU profiling in Ubuntu 22.04

### ISSUE THREAD

**Issue by lengocthuong15** [KDAB/hotspot#519]
**Describe the bug**
When I run the program and check for off-CPU profiling, an error shows up, it is about  invalid event sched:sched_switch

**To Reproduce**

1. Open Hotspot UI, record data
2. Select Attach to Processes
3. Tick on: Elevate Privilege and Off-CPU profiling
4. And error shows: Failed to record perf data, error code 129
```
$ perf record -o /home/build/perf.data --call-graph dwarf --event cycles --switch-events --event sched:sched_switch --pid 1648
event syntax error: 'sched:sched_switch'
                     \___ unsupported tracepoint

libtraceevent is necessary for tracepoint support
Run 'perf list' for a list of valid events
```

**Expected behavior**
Can record data with Off-CPU profiling

**Version Info (please complete the following information):**

- Linux Kernel version:6.2.0-34-generic
- perf version:6.2.16
- hotspot version (appimage? selfcompiled?): Ubuntu 22.04. Install from source list

**Comment by lievenhey** [comment]
Can you check if `perf` is compiled with with `libtraceevent` support? `perf version --build-options`

On my ubuntu VM it reports
```
....
libtraceevent: [ OFF ]  # HAVE_LIBTRACEEVENT
```
in this case you have to build perf yourself
