### ISSUE TITLE
Find .debug files in same directory as binary

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#52]
When running hotspot on something that has separate .debug files, one needs to pass "-DebugPaths ." explicitly. This shouldn't be needed, for each executable and library hotspot should first check if such a file is found in the same directory.

/usr/lib/debug should also be in the default path list if it isn't already.

**Comment by milianw** [comment]
`--appPath` is now used to find debug link files. And https://codereview.qt-project.org/194601 makes the need to pass any folder at all obsolete for the common case.

**Comment by milianw** [comment]
And do note that `/usr/lib/debug` and similar paths are set as the default already.

**Comment by milianw** [comment]
fixed now by 

```
commit 34e2c93b4afe98d034afb2c33eb7513d4d30b4db (master)
Author: Milian Wolff <milian.wolff@kdab.com>
Date:   Sun May 14 01:55:30 2017 +0200

    Extend fallback code to find debug link file based on original path
    
    By remembering the path under which a file was originally referenced
    in the mmap call, we can use this information to find debug link
    files. I.e. we will now try to find the debug link file in the original
    binary target folder, which is where this debug link file often resides.
    
    This is useful for lazy people like me who don't want to set the
    application path every time they use perfparser.
    
    Change-Id: I8e33f137b186ed857b9b4da1d0618d0ae903d0cd
```

in perfparser
