### ISSUE TITLE
Bug in Caller/Callee: Column sorting is reset on each filtering

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#531]
**Describe the bug**
Applying a filter resets the sorting column to be Self (decreasing)

**To Reproduce**

1. Go to Caller/Callee
2. Change Order, for example sorting by binary
3. Then choose one symbol -> exclude by symbol
4. See error: the sorting is reset

**Expected behavior**
Filtering changes only the view's data, not its view attributes.

**Version Info:**
current appimage of today, hotspot-v1.4.1-192-g73c5701-x86_64.AppImage (Hotspot 1.4.80, using QT5.15.11 and [presumingly](https://github.com/KDAB/hotspot/commit/b99eabe766b30e0658ed974ef54fda4004a2d1b6#diff-cb941a3d1c2e2c34f655153338df8e21205daffd6f08a6b968cde1598182400b) KF5 v5.110.0 and KDDockWidgets 1.7)

**Comment by lievenhey** [comment]
Hi, I just rechecked this and it seems that this was fixed. I will close it for now. Feel free to reopen if it still exists.

**Comment by lievenhey** [comment]
found it: 99cafd655048084ca88005664d2a7f5417dac823 sneaked in there
