### ISSUE TITLE
Disassembly view: add "go to line/address" command

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#541]
**Is your feature request related to a problem? Please describe.**
I've recognized that I often "scroll around" to switch between several parts of a function. So far it is necessary to remind the place in the horizontal scroll bar, then get back using this (or use the new search feature).

**Describe the solution you'd like**
The easiest option to "skip around" would be a general-use function "go to", ideally with the default shortcut CTRL+G (in the "active" window, like it is done for CTRL+F).

**Additional context**
As there may not be the exact line, and especially not the exact address: position to the first line after the specified one, if there isn't one then position to the last.

Additional to the general usability it would also provide a workaround for #515.

**Comment by lievenhey** [comment]
You can click on a line to go to the corresponding one in the other view.

**Comment by lievenhey** [comment]
Waht do you mean by "go to function"? Enter an address and jump there? Or something like: put a marker here and then some shortcuts to jump between markers?

**Comment by GitMensch** [comment]
On the right:
* enter address and go there
* on the left: enter a line number and go there

both _seem_ easy - but I have no clue how to do that.

Nonetheless, your idea of "adding favorite points to fast switch between" is also good, you may want to create a separate issue for that.

But #528 seems to be much more useful than the favorites and may be implemented first.

**Comment by GitMensch** [comment]
@lievenhey is there any chance to tackle this and/or #515 next?

**Comment by lievenhey** [comment]
sure
