### ISSUE TITLE
Should we request `--visualize-jumps` even if it is disabled in the settings?

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#544]
https://github.com/KDAB/hotspot/blob/cdc66a49c80020905fd3ecdd1236e2dcf5014fb3/src/models/disassemblyoutput.cpp#L297-L302 currently always checks for that feature.
The main question is: Should we request that at all if the settings disabled the view of this data? Benefit of keeping as-is: it is easy to enable the column upon request. The downside, which I think is bigger and would be a reason to check the setting before trying to add it: the objdump is faster and creates less output we need to parse later (and then kin of throw away by not having that column visible).

I do volunteer to make that change, just wanted to check before if that's reasonable.

**Comment by milianw** [comment]
I think we should keep it, as we would otherwise have to rerun `objdump` when the setting is changed or the column gets hidden.

to convince me otherwise: can you share some numbers that show what kind of difference we are talking here? I doubt it's that big a deal to query this data...
