### ISSUE TITLE
SIGSEGV  for disasembly when switched

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#553]
**Describe the bug**
Crash

**To Reproduce**

1. Create an empty file do_objdump.sh and make that executable
2. open recording
3. choose disassembly (doesn't matter what function)
4. see disassembly
5. switch view
6. go to settings, change objdump to "do_objdump.sh"
7. choose disassembly again
8. crash 

**Expected behavior**
A clear error message

**Version Info (please complete the following information):**

- hotspot-v1.4.1-213-g7b0b0b1-x86_64.AppImage

**Comment by milianw** [comment]
can you provide a backtrace please?

**Comment by GitMensch** [comment]
Can't reproduce with current appimage, seems the adjustments for objdump fixed that.
