### ISSUE TITLE
allow to specify objdump + perf on command line

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#556]
**Is your feature request related to a problem? Please describe.**
Different recordings need different objdump binaries. To provide that Hotspot already provides a setting for both this and perf.
It would be nice to be able to specify that on the command line, too; as is the case for other options.

**Describe the solution you'd like**
command line options for those, possibly `--perf` and `--objdump`; this would also allow to create local aliases that call hotspot with the right settings for seldom uses, removing the need to set, then later unset

**Describe alternatives you've considered**
Set them in the configuration, then unset when not needed anymore.

**Additional context**
I you want me to, I could try creating a PR, but I don't see how, if at all, I could add a reasonable automated test for that.

**Comment by lievenhey** [comment]
Better idea: provide an option to select to configuration via command line. That would take care of all the other stuff (sysroot, ...) too

**Comment by GitMensch** [comment]
And how would you provide the configuration?
The idea of adding the two missing configuration options is to be able to "manually" provide those configurations via aliases.

**Comment by GitMensch** [comment]
@milianw Would you accepta PR that adds `--perf` / `--objdump`?

**Comment by GitMensch** [comment]
> Would you accept a PR that adds `--perf` / `--objdump`?

ping @milianw about that question and ping @lievenhey about the specs for the configuration.
