### ISSUE TITLE
perfparser: add elfutlis version info to `--version` (and its debug symbols in the debuginfo appimage package)

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#560]
**Is your feature request related to a problem? Please describe.**
I'm inspecting issues seen in perfparser and find it hard to go on with the appimage provided version.

One of the reasons is that appimage creation uses centos7 (I _guess_ it is still at "debuginfod only for centos8+9 state) and more important: the elfutils used, which make the biggest part of perfutils (`perf record` shows 98.5% spent in hotspot-perfparser is in `PerfRecordSample::PerfRecordSample(PerfRecordSample&&)`), is statically linked, so not well visible with `ldd` either.

**Describe the solution you'd like**
Include elfutils version in an extra line in `hotspot-perfparser` - both to make it more clear what is used and to give credits to the library that seems to do most of the actual work.
Furthermore it would be very good if the appimage debuginfo download could include the elfutils debuginfo package.

**Describe alternatives you've considered**
None.

**Comment by GitMensch** [comment]
The first part was tackled with by @lievenhey with https://github.com/KDAB/perfparser/commit/9b3ff414f79c68920a5fde0d6809e84ac358101c and will be solved on the next perfparser revision update.
The second one needs to be handled in creating the debuginfo appimage package (but I haven't looked how this is created so far).

**Comment by lievenhey** [comment]
The debug symbols are available at: https://github.com/KDAB/hotspot/releases/tag/qt-debuginfo
