### ISSUE TITLE
Adopt Arch Linux package file

### ISSUE THREAD

**Issue by jonhoo** [KDAB/hotspot#58]
I just published an Arch Linux package file for `hotspot`. May be worth adopting it into the repository so that it can be maintained as the program develops: https://aur.archlinux.org/packages/hotspot-git/

**Comment by jonhoo** [comment]
The build script itself is at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hotspot-git

**Comment by milianw** [comment]
Sorry, but despite being an ArchLinux user I don't feel like maintaining distribution packages. An AppImage I could see, but anything else is too distro specific.

**Comment by milianw** [comment]
That said, please feel free to open a Wiki page with links to such resources.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by probonopd** [comment]
Started working on it [here](https://github.com/probonopd/hotspot/blob/patch-1/.travis.yml), but running into compilation issues:

```
/home/travis/build/probonopd/hotspot/src/parsers/perf/perfparser.cpp:38:37: fatal error: ThreadWeaver/ThreadWeaver: No such file or directory
 #include <ThreadWeaver/ThreadWeaver>
                                     ^
compilation terminated.

Full build log [here](https://api.travis-ci.org/jobs/256721459/log.txt?deansi=true).
```

**Comment by milianw** [comment]
@probonopd see https://github.com/KDAB/hotspot/pull/75 for travis ci support

**Comment by agauniyal** [comment]
+1 for AppImage. Installing on Arch Linux pulls many unnecessary dependencies that start with *k* :p

**Comment by milianw** [comment]
@agauniyal not sure what you are trying to say with your comment - is it a "thank you" to probonopd and me for adding an AppImage? It does exist already, so I wonder why you commented on this issue which is closed for some time now?

**Comment by agauniyal** [comment]
@milianw yes it was a gesture of appreciation from my end :)

**Comment by probonopd** [comment]
An AppImage is available from the GitHub Releases page, so I think this can be closed. Thank you very much!
