### ISSUE TITLE
source view with strange "Util" context menu

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#591]
There's very likely some nice function there, but I have no idea what.
![grafik](https://github.com/KDAB/hotspot/assets/6699539/017eae24-7969-4905-80e9-15d877c62bd1)

... actually: I think there was an "open in editor" in there.

(this is the result using the most current appimage)

**Comment by lievenhey** [comment]
Don't mindlessly replace `QApplication::translate` with `tr` this somehow compiles but doesn't work. Working on it.
