### ISSUE TITLE
.deb (and maybe other) distribution packaging

### ISSUE THREAD

**Issue by osmoc** [KDAB/hotspot#60]
Would be cool if such a useful tool could be installed via standard distribution package manager. I see some steps in that direction already happening with #58 but I'm more interested in .deb

As an intermediary step it could be made available via OBS or Launchpad.

**Comment by milianw** [comment]
Please talk to your distributor. I'm sure they are interested in packaging it up, too. Now that there's a first release, they usually are quite quick about it.
