### ISSUE TITLE
Latest AppImage download without GitHub account

### ISSUE THREAD

**Issue by HybridDog** [KDAB/hotspot#605]
**Describe the bug**

The Readme explains a way to download the latest AppImage from the build jobs, but it does not work unless the reader is registered and logged in at GitHub, which is not mentioned.

> Head over to our list of AppImage build jobs. When you click on a job, you'll see a page with an "Artifacts" section that contains an "appimage" binary you can then download.

**To Reproduce**

1. Log out from GitHub
2. Go to the [mentioned link](https://github.com/KDAB/hotspot/actions/workflows/build-appimage.yml?query=branch%3Amaster)
3. Click on the first "workflow run result"
4. Scroll down to "Artifacts" and click on "appimage" next to the wireframe cube icon
5. Observe how "appimage" is not a link but only text which can be marked

**Expected behavior**
The Readme could mention that downloading the build artifact requires a GitHub account or explain another way to download it.

**Screenshots**
![2024-02-22-110536_990x373_scrot](https://github.com/KDAB/hotspot/assets/3192173/27f831e9-6c43-4dd9-abef-6f744f7ce191)

**Version Info (please complete the following information):**

- Linux Kernel version: not applicable
- perf version: not applicable
- hotspot version (appimage? selfcompiled?): master
- if self-compiled hotspot, what version of elfutils: not applicable

**Additional context**
Downloading the older AppImage from the releases webpage works without GitHub account.

**Comment by GitMensch** [comment]
There is no reasonable way to provide the Appimage _on each CI build **outside** of the CI artifacts_ (which is needed for the download) - but it would definitely be useful to update the CI image on the release page from time to time, kind of "stable appimage" (which may be a new release).

As I personally see some issues [already worked on] that break the Disassembly view, I'd suggest to do that afterwards.

Another option is to run a nightly/weekly workflow to update the release [as pointed out by @Kagami](https://github.com/actions/upload-artifact/issues/51#issuecomment-1893927846)

> ```yaml
> - name: Release nightly
>   uses: softprops/action-gh-release@v1
>   with:
>     prerelease: true
>     name: nightly
>     tag_name: nightly
>     files: file.txt
>     fail_on_unmatched_files: true
> ```
> 
> And instruct your users to download from `https://github.com/OWNER/REPO/releases/download/nightly/file.txt` Example [here](https://github.com/Kagami/ninnin/blob/0aa2e0638b28315da9bd44e3804d5c8ab4fbd08b/.github/workflows/build.yml).
> 
> That file.txt will be updated on every commit, keeping single pre-release release without cluttering with other releases and `latest` stable release.
> 
> As a bonus it won't disappear if you don't commit for 90 days (as with artifacts).

With a similar example workflow on: https://github.com/kernelkit/infix/blob/main/.github/workflows/build.yml

**Comment by milianw** [comment]
we finally have a new stable release (https://github.com/KDAB/hotspot/releases/tag/v1.5.0). I would really like to see someone work on automated regular public continuous releases. I think @lievenhey is already looking into this.
