### ISSUE TITLE
After opening, cargo command cannot run until path changes

### ISSUE THREAD

**Issue by qarmin** [KDAB/hotspot#609]
**Describe the bug**
When debugging cargo, after next run I cannot run cargo, until I change path and revert it back.

https://github.com/KDAB/hotspot/assets/41945903/4a84263b-5593-4614-b6fb-704583c091e5

Start Recording at start is disabled, but should be enabled

**Version Info (please complete the following information):**

- hotspot version (appimage? selfcompiled?): https://github.com/KDAB/hotspot/commit/271a781cff2514f3557926950087a0ac0f6dede7
- if self-compiled hotspot, what version of elfutils: appimage

**Comment by milianw** [comment]
I don't see it in the video, can you make it more obvious? does it only happen with cargo or with all applications?

**Comment by qarmin** [comment]
Look at "Start Recording" button - is not enabled, but should be.

The problem only happens with  `cargo`, `nemo` etc. commands, but not with with full paths like `/home/user/.cargo/cargo` or `/usr/bin/nemo`

Steps to reproduce:
- Open hotspot
- in Application use "nemo"
- in Working Directory use "/home/user"
- run profiling
- close app
- open again hotspot
- "Start Recording" button is disabed (here is bug - this should be enabled)
- add space after "nemo" and remove it
- "Start Recording" button is enabled

The same but with full path
- Open hotspot
- in Application use "/usr/bin/nemo"
- in Working Directory use "/home/user"
- run profiling
- close app
- open again hotspot
- "Start Recording" button is enabled (proper behavior)

![Screenshot from 2024-03-12 15-48-18](https://github.com/KDAB/hotspot/assets/41945903/d91527fd-b526-47dd-ae5f-f29f42600c46)
![Screenshot from 2024-03-12 15-48-23](https://github.com/KDAB/hotspot/assets/41945903/410d28fd-17ed-40e5-9499-9872f39a615f)

**Comment by milianw** [comment]
thanks, now I see it and can reproduce it. will fix
