### ISSUE TITLE
1.0 github tarbal does not build

### ISSUE THREAD

**Issue by fenrus75** [KDAB/hotspot#61]
github does not include git submodules in its tagged tar files, and thus you get

CMake Error at CMakeLists.txt:9 (message):
  The perfparser git submodule is not initialized.
  Please run the following commands in the source directory
  (/builddir/build/BUILD/hotspot-1.0.0):
      git submodule update --init --recursive

when trying to build from it

**Comment by milianw** [comment]
Ouch, indeed - I'll fix that up. Thanks for the notification

**Comment by milianw** [comment]
For now, I've added the perfparser source tarballs to the release page, seems like I cannot easily tell GitHub to change the source tarball or to include the submodule

**Comment by milianw** [comment]
https://github.com/KDAB/hotspot/releases/tag/v1.0.0 now includes a self-contained package, let's hope I remember that for the next releases ;-) If you, or anyone else, has an idea on how to improve that situation, I'm all ears.

Thanks

**Comment by fenrus75** [comment]
fwiw I just tried the hotspot-1.0 tar file in the releases tab and it also does not work; digging into why

**Comment by fenrus75** [comment]
if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/perfparser/.git" )


that's why. to be honest, that check is slightly evil.....

**Comment by milianw** [comment]
damn yes - I'll have to come up with a different way to do that

**Comment by milianw** [comment]
ok, I hope the release tarballs work now - I'll also make sure that this mess up doesn't happen for future releases

cheers, thanks for the report again
