### ISSUE TITLE
Hotspot only displays cpu percentages, not cycles on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by GarryMorrison** [KDAB/hotspot#614]
I am using "perf record -e cycles ./my-prog" but I am only getting CPU percentages in hotspot, not cycles.

Steps:
1. perf record -e cycles ./myprog
2. hotspot
3. Click on Top Down
4. Event Source only shows cpu-clock
5. and results only show cpu % not cycle counts

I was hoping/expecting to see cycle counts as an option in the event sources.

- Kernel version: 6.5.0-27-generic
- perf version 6.5.13
- hotspot 1.3.0 (installed using Ubuntu apt)

**Comment by milianw** [comment]
You can hover each place to see the absolute values.

Note that the decision to show percentages is a deliberate one: perf is a sampling based profiler, as such it does not give an accurate absolute measurement of cycles on a per-function basis. The relative number on the other hand is statistically accurate (given enough samples)
