### ISSUE TITLE
ECM undeclared dependency

### ISSUE THREAD

**Issue by nh2** [KDAB/hotspot#62]
Hi, "ECM" (`extra-cmake-modules` on Debian/Ubuntu) seems to be a dependency but is not in the dependencies list. Mind adding it?

Without it I get

```
CMake Error at CMakeLists.txt:49 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 1.0.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake
```

Thanks!

**Comment by milianw** [comment]
Thanks, there are some more KF5 libs you'll need to. I've extended the README.md accordingly now

**Comment by nh2** [comment]
Cool thanks.

I'm adding hotspot to nixpkgs here: https://github.com/NixOS/nixpkgs/pull/27181

After that, you'll be able to install it with `nix-shell -p hotspot`.
