### ISSUE TITLE
Crash(Assertion failure) when opening large data

### ISSUE THREAD

**Issue by kxxt** [KDAB/hotspot#629]
**Describe the bug**
hotspot crashed when opening a very large data file(1.72GB).

**To Reproduce**

```
hotspot hotspot_crash.data &> ~/hotspot.log
```

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**

- Linux Kernel version: `Linux spectre 6.8.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000 x86_64 GNU/Linux`
- perf version: perf version 6.7-3
- hotspot version (appimage? selfcompiled?): 1.4.80 from chaotic-aur (package version 20240412-1)
- if self-compiled hotspot, what version of elfutils:

**Additional context**

```
unhandled event type 13   unknown type
/usr/include/c++/13.2.1/valarray:588: const _Tp& std::valarray<_Tp>::operator[](std::size_t) const [with _Tp = long long int; std::size_t = long unsigned int]: Assertion '__i < this->size()' failed.
zsh: IOT instruction (core dumped)  hotspot hotspot_crash.data
```

[hotspot.log](https://github.com/KDAB/hotspot/files/15199681/hotspot.log)

Thanks for creating such a nice tool for analyzing performance. I really love using it. Large files are usually difficult to handle in GUI applications, which I think is what this bug reveals.

hotspot_crash.data is saved by [cargo-flamegraph](https://github.com/flamegraph-rs/flamegraph) command.

It is attached here in a zstd compressed form. Due to github's limitation, it is again compressed with gzip before uploading:
[hotspot_crash.data.zst.gz](https://github.com/KDAB/hotspot/files/15199813/hotspot_crash.data.zst.gz)

**Comment by lievenhey** [comment]
Hi,
thanks for finding this bug. I hope I have found the issue. I was able to open your dump with the following [appimage](https://github.com/KDAB/hotspot/actions/runs/9061920765).

Can you try again with that version to see if it fixed the bug?

**Comment by kxxt** [comment]
> Hi, thanks for finding this bug. I hope I have found the issue. I was able to open your dump with the following [appimage](https://github.com/KDAB/hotspot/actions/runs/9061920765).
> 
> Can you try again with that version to see if it fixed the bug?

Hi, thanks for your fix. I can confirm that the bug is fixed by your PR.
