### ISSUE TITLE
Problematic name

### ISSUE THREAD

**Issue by ghost** [KDAB/hotspot#63]
I think the name hotspot should be changed to something else. Very hard to search, trademarked in both software and hardware, and people already think of something else when they hear hotspot.

(Noticed these concerns on reddit, agreed, figured an issue was worthwhile)

**Comment by milianw** [comment]
I personally don't think it's such a big deal, but I'm open for suggestions. Note that I'm against calling it any combination of `qt` and `perf`. Not only is it a lame name, it's also pretty bad when said out loud: "cute perf" is too close to something I don't want to be associated with ;-)

**Comment by notsonotso** [comment]
FlameSpot

**Comment by pankajp** [comment]
> Note that I'm against calling it any combination of qt and perf

How about `perfeqt` 😛

**Comment by notsonotso** [comment]
@pankajp It's not perfect.

**Comment by StringEpsilon** [comment]
@notsonotso 

Based on another reddit comment: BarbeCute / BBQT.

**Comment by milianw** [comment]
it has worked with this name for over a year by now, the name won't change
