### ISSUE TITLE
Can/will it be possible to use hotspot with framepointers?

### ISSUE THREAD

**Issue by meastp** [KDAB/hotspot#646]
Hi,

I'm a novice on profiing, so this might be a silly question / I might have misunderstood what the requirements are, but:

> First of all, record some data with perf. To get backtraces, you will need to enable the dwarf callgraph mode:

Is it possible / will it be possible to use frame pointers instead? Now that recent distributions build with frame pointers[1], it would be useful to be able to use frame pointers instead of dwarf.

[1] https://www.brendangregg.com/blog/2024-03-17/the-return-of-the-frame-pointers.html

**Comment by milianw** [comment]
You can use frame pointers, hotspot supports them just fine. If not, report a bug.

Just make sure that that _all_ code, including thirdparty libraries, has them. This is not yet the case for a lot of distros or binary blobs.
