### ISSUE TITLE
Couldn't find architecture of any ELF

### ISSUE THREAD

**Issue by mgaunard** [KDAB/hotspot#66]
I tried to load a perf.data generated on a CentOS 6 box into my Ubuntu workstation.
I get this error repeatedly on stdout
18087 failed to attach state Couldn't find architecture of any ELF

And all symbols appear as ??

Is this a problem with incompatible perf.data files across kernel versions?

**Comment by mgaunard** [comment]
Output is not much better with perf report, so not really a hotspot problem

**Comment by milianw** [comment]
this sounds like no mmap records are present, or the corresponding files are not found? Sounds like a pretty broken perf setup
