### ISSUE TITLE
Could not find plugin konsolepart (v1.5.1)

### ISSUE THREAD

**Issue by khismatullin** [KDAB/hotspot#661]
**Describe the bug**
Launch AppImage v1.5.1

**To Reproduce**

1. sudo ./hotspot-v1.5.1-x86_64.AppImage

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**

- Linux Kernel version: 6.5.0-41-generic
- perf version: 6.5.13
- hotspot version (appimage):

**Additional context**
i try resolve with commands:
  sudo apt-get install konsole-kpart konsole-kpart-dbgsym

**Comment by milianw** [comment]
this is probably because you are running on a kf6 distro but the appimage tries to load a kf5 konsole part.

what distro do you use? is there no stable hotspot image you could use instead?

furthermore note that this is a purely optional dependency - everything will work fine without it.

**Comment by milianw** [comment]
no response, closing this
