### ISSUE TITLE
Disassembly view not working

### ISSUE THREAD

**Issue by amotzop** [KDAB/hotspot#670]
I'm trying to use the AppImage1.5.1 version (on the Ubuntu 24.04 release).
In order to make it work I had to run it with `QT_QPA_PLATFORM=wayland`,  otherwise it doesn't launch.
But when I open it there is no disassembly view and every option related to it is grayed out and not clickable.

**Screenshots**
![disassembly_option_on_function_missing](https://github.com/user-attachments/assets/ebb22ddd-3eb5-4790-9bb1-105712bcddc8)
![disassembly_view_missing](https://github.com/user-attachments/assets/f2f86c8e-4236-4d91-965d-adb0217df64a)

**Version Info (please complete the following information):**

- Linux Kernel version: 6.8.0
- perf version: 6.8.8
- hotspot version (appimage? selfcompiled?): AppImage v1.5.1

**Comment by GitMensch** [comment]
The disassembly view is only visible after you use it for the first time. To do so you need to right click a *symbol*, for example in caller/callee or the flamegraph and use the Disassembly feature there.

**Comment by amotzop** [comment]
Oh, didn't see that.
But it seem to only work for the "main" function, and I don't see any percentages attributed to any assembly opcode (the "cycles:P" column is empty) (using `perf annotate` doe's give some opcodes high percentages, but is less readable than hotspot's output)

**Comment by milianw** [comment]
Is this a variant of https://github.com/KDAB/hotspot/issues/671 maybe? Otherwise, can you share some code and show us how to reproduce the issue from your last comment?

**Comment by milianw** [comment]
closing as duplicate for now, please reopen if this is something else
