### ISSUE TITLE
Broken command in off-CPU recipe in documentation

### ISSUE THREAD

**Issue by jabcross** [KDAB/hotspot#675]
Command: 

`perf record -o perf.data -e cycles -e shed:sched_switch --switch-events --sample-cpu -m 8M --aio -z --call-graph dwarf $(realpath ./extract)`

Output:

```
event syntax error: 'shed:sched_switch'
                     \___ unknown tracepoint

Error:	File /sys/kernel/tracing//events/shed/sched_switch not found.
Hint:	Perhaps this kernel misses some CONFIG_ setting to enable this feature?.

Run 'perf list' for a list of valid events

 Usage: perf record [<options>] [<command>]
    or: perf record [<options>] -- <command> [<options>]

    -e, --event <event>   event selector. use 'perf list' to list available events

```

Note the double `/`. The file does exist.

**Comment by GitMensch** [comment]
That's from the `perf` tool which is part of the Linux Kernel. Please create an issue upstream (kernel mailing list) with output of `perf --version` or check with your GNU/Linux distribution (support/community).

Just FYI - this is where it comes from, exactly:
https://github.com/torvalds/linux/blob/88fac17500f4ea49c7bac136cf1b27e7b9980075/tools/lib/api/fs/tracing_path.c#L152-L155

This issue should be closed here.

**Comment by milianw** [comment]
You are lacking permissions to the tracefs file system. Run the elevate permissions script or use the built-in GUI to elevate your permissions temporary.
