### ISSUE TITLE
Timeline is not readable with a dark theme

### ISSUE THREAD

**Issue by lievenhey** [KDAB/hotspot#682]
![grafik](https://github.com/user-attachments/assets/2a5302a4-e05b-4ea6-9daa-719cf3671863)
it also looks weird

**Comment by milianw** [comment]
I cannot reproduce this, what color scheme are you using?

![Screenshot_20241111_201937](https://github.com/user-attachments/assets/72fd8561-29fd-4d32-a58f-4b5e26ca548c)

**Comment by lievenhey** [comment]
But I also gues that `xxx` should be the actual time and the rest should be offsets like `-10ms` and `+10ms`.

**Comment by milianw** [comment]
yes it works as designed by @koenpoppe (see PrefixTickLabels), I am tempted to close this or is there an action item for you here @lievenhey?

**Comment by lievenhey** [comment]
clising is
