### ISSUE TITLE
Increase support for LTS distros such as RHEL 7 and Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nevion** [KDAB/hotspot#79]
These distros are still where alot of development happens and despite some of the dated libs, are overall keeping up fairly well, this iteration.  Qt is also available as a precompiled installation - so tools like qtcreator can run even on something as old as RHEL (+CentOS) 6.  The only real issue is the dependency that is a big deal is KDE SC, as far as I can tell.

CentOS/RHEL7/Ubuntu 16.04 are important support targets because of how heavily they are involved in research and non-profit usages and where it can be important to need a profiler such as hotspot.

Can another way forward be found that keeps hotspot's developer's happy but extends support to these distributions?

**Comment by milianw** [comment]
Yes, the solution for this would be an AppImage, see https://github.com/KDAB/hotspot/pull/76

**Comment by milianw** [comment]
We now have AppImages which should work on Ubuntu 14.04 and higher

**Comment by nevion** [comment]
@milianw how to install?

**Comment by milianw** [comment]
Use the latest build of the master branch on https://travis-ci.org/KDAB/hotspot/branches, then scroll all the way down to find a link of the form `https://transfer.sh/rUDgX/Hotspot-git....-x86_64.AppImage`. Download that, make it executable, run.

**Comment by milianw** [comment]
Oh and the upcoming 1.1 release of course will get a proper AppImage attached to the release notes.
