### ISSUE TITLE
Color flamegraphs by various criteria

### ISSUE THREAD

**Issue by tmcguire** [KDAB/hotspot#80]
In http://www.brendangregg.com/blog/2017-07-30/coloring-flamegraphs-code-type.html, Brendan Gregg shows color of flamegraphs, with different colors for Java code, native C++ code and kernel code.

I suggest hotspot should do the same. Maybe even with a configurable combobox to toggle between various schemes, with some ideas:
- user vs kernel
- one color for each process in a multi-process perf.data file
- color per DSO - would be useful to immediately see which parts of the stack are the QML engine, which parts are the application itself, which parts are QtCore etc
- user code vs system libraries vs kernel
  - Needs criteria to specify "user code" - all DSOs outside of /usr and /lib? V-Tune probably does something similar with its "user code +1" option

Unlike Brendan Gregg, I don't think inlined function should have a different color, as for me if a function is inlined or not is an implementation detail.

**Comment by milianw** [comment]
agreed, that would be a very good improvement

**Comment by tmcguire** [comment]
See also https://github.com/KDAB/hotspot/issues/107 for an idea of coloring the cells according their on-cpu and off-cpu percentages.
