### ISSUE TITLE
Problems with building.

### ISSUE THREAD

**Issue by dendibakh** [KDAB/hotspot#81]
Hello,

I'm trying to build the app, but it fails with this error:
`
[  3%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/main.cpp.o
/home/denis/workspace/hotspot/3rdparty/perfparser/app/main.cpp: In function ‘int main(int, char**)’:
/home/denis/workspace/hotspot/3rdparty/perfparser/app/main.cpp:115:37: error: ‘listSeparator’ is not a member of ‘QDir’
             .arg(QDir::separator(), QDir::listSeparator(), QDir::homePath());
`
I'm doing exactly how it's written in readme. All dependencies were installed and cmake executes with no errors.
Ubuntu 16.04, gcc 5.4.

**Comment by krf** [comment]
You need at least Qt 5.6 to build Hotspot (and perfparser) for the moment.

I don't think we do want to go lower than that Qt version, but I'm not sure what the maintainer thinks about it.

**Comment by milianw** [comment]
Agreed, the Qt version is too old (but we need to improve the CMake check to say so explicitly). An AppImage (we are working on that) will help for older distros
